alter table TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION drop constraint TMO_ACCT_EXEMPTION_PK;
alter table TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION add constraint TMO_ACCT_EXEMPTION_PK PRIMARY KEY (CUSTOMER_REF);
commit;