DELETE FROM GENEVABATCHUSER.DUF_M2M_DATA;
COMMIT;
DELETE FROM GENEVABATCHUSER.DUF_MVNO_DATA;
COMMIT;
 ALTER TABLE 
   GENEVABATCHUSER.DUF_M2M_DATA
MODIFY 
( 
   UPLINK_VOLUME    INTEGER,
   DOWNLINK_VOLUME  INTEGER
);
ALTER TABLE 
   GENEVABATCHUSER.DUF_MVNO_DATA
MODIFY 
( 
   UPLINK_VOLUME    INTEGER,
   DOWNLINK_VOLUME  INTEGER
);