ALTER TABLE GENEVA_ADMIN.ACCOUNTPAYATTRIBUTES 
ADD WEB_PORTAL_USER VARCHAR2(50); 
ALTER TABLE GENEVA_ADMIN.ACCOUNTPAYATTRIBUTES 
ADD CREATED_DTM DATE; 
ALTER TABLE GENEVA_ADMIN.ACCOUNTPAYATTRIBUTES 
ADD CANCELLED_DTM DATE; 