insert into tmobile_custom.TMO_INVOICE_DESC_ORDERING (EVENT_SUMMARY_ID, COST_BAND_DESC, EVENT_CLASS_NAME, ORDER_NUM, DESCRIPTION, LINE_ITEM_TEXT)
values (89, 'GPRS', 'High', 570, 'GPRS', '%GPRS');
commit;

