CREATE OR REPLACE VIEW TMOBILE_CUSTOM.TMO_BILLING_HISTORY_VIEW AS
SELECT ACCOUNT.CUSTOMER_REF,
     BILLSUMMARY.ACCOUNT_NUM,
     BILLSUMMARY.BILL_SEQ,
     BILLSUMMARY.INVOICE_NUM,
     BILLSUMMARY.BILL_DTM,
     BILLSUMMARY.BILL_STATUS BILL_STATUS_ID,
     DECODE(BILLSUMMARY.BILL_STATUS,1,  'Created',
          7  ,'Pending event deletion',  
             8  ,'Events deleted') BILL_STATUS,
             EVENTTYPE ,
             EVENTMNY,BILLSUMMARY.INVOICETYPE,BILLSUMMARY.INVOICEPERIOD
    FROM (SELECT ACCOUNT_NUM, BILL_SEQ, INVOICE_NUM, BILL_DTM, BILL_STATUS BILL_STATUS_ID, BILL_STATUS, INVOICE_NET_MNY+INVOICE_TAX_MNY EVENTMNY, 'BILL' EVENTTYPE,
                  case when bill_type_id = 1 then 'Periodic'
                       when bill_type_id = 4 then 'Final'
                        end INVOICETYPE,
                CONCAT(CONCAT(TO_CHAR(START_OF_BILL_DTM,'MM/DD/YYYY') , '-') , TO_CHAR((BILL_DTM-1),'MM/DD/YYYY')) AS  INVOICEPERIOD
        FROM GENEVA_ADMIN.BILLSUMMARY where BILL_STATUS in (1,7,8) and bill_type_id in (1,4)
      ) BILLSUMMARY
    LEFT JOIN GENEVA_ADMIN.ACCOUNT
    ON BILLSUMMARY.ACCOUNT_NUM = ACCOUNT.ACCOUNT_NUM and BILL_STATUS_ID in (1,7,8)
     WITH READ ONLY;

    GRANT SELECT ON "TMOBILE_CUSTOM"."TMO_BILLING_HISTORY_VIEW" TO "UNIF_ADMIN";