
-- CDR details data api
BEGIN
  execute immediate 'DROP TABLE TMOBILE_CUSTOM.CDR_TMO_ACCT_MAPPING';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
CREATE TABLE TMOBILE_CUSTOM.CDR_TMO_ACCT_MAPPING 
(
      CDR_FORMAT VARCHAR2(20),
      MAPPING_ID NUMBER(5),
      TABLE_NAME VARCHAR2(40)
);
GRANT SELECT ON TMOBILE_CUSTOM.CDR_TMO_ACCT_MAPPING TO UNIF_ADMIN;      
insert into TMOBILE_CUSTOM.CDR_TMO_ACCT_MAPPING (CDR_FORMAT, MAPPING_ID, TABLE_NAME)
values ('M2M', 1, 'DUF_M2M_DATA');

insert into TMOBILE_CUSTOM.CDR_TMO_ACCT_MAPPING (CDR_FORMAT, MAPPING_ID, TABLE_NAME)
values ('M2M', 0, 'DUF_M2M_VOICE');

insert into TMOBILE_CUSTOM.CDR_TMO_ACCT_MAPPING (CDR_FORMAT, MAPPING_ID, TABLE_NAME)
values ('MVNO', 1, 'DUF_MVNO_DATA');

insert into TMOBILE_CUSTOM.CDR_TMO_ACCT_MAPPING (CDR_FORMAT, MAPPING_ID, TABLE_NAME)
values ('MVNO', 0, 'DUF_MVNO_VOICE');

COMMIT;


