DROP VIEW TMOBILE_CUSTOM.TMO_PAYMENT_VIEW;

CREATE OR REPLACE FORCE VIEW TMOBILE_CUSTOM.TMO_PAYMENT_VIEW
(
   CUSTOMER_REF,
   ACCOUNT_NUM,
   PAYMENT_SEQ,
   PAYMENT_DAT,
   PAYMENT_MNY,
   PAYMENT_TYPE_ID,
   CREATED_DTM,
   -- PAYMENT_STATUS,
   PAYMENT_TXT,
   ALT_PAYMENT_MNY,
   ALT_CURRENCY_CODE,
   BATCH_ID,
   ACCOUNT_PAYMENT_REF,
   BILL_SEQ,
   BILL_DATE,
   INVOICE_NUM,
   STATUS,
   PHYSICAL_PAYMENT_SEQ,
   CREATED_BY,
   START_BILL_DTM,  -- ADDED for TMOGENESIS-21613 : RBM Custom API: Query API. start_dat, start_of_bill_dtm
   PAYMENT_METHOD_ID, 
   PAYMENT_METHOD_NAME
)
AS
   SELECT DISTINCT  ACCOUNTPAYMENT.CUSTOMER_REF,
            ACCOUNTPAYMENT.ACCOUNT_NUM,
            ACCOUNTPAYMENT.ACCOUNT_PAYMENT_SEQ AS PAYMENT_SEQ,
            ACCOUNTPAYMENT.ACCOUNT_PAYMENT_DAT AS PAYMENT_DAT,
            ACCOUNTPAYMENT.ACCOUNT_PAYMENT_MNY AS PAYMENT_MNY,
            ACCOUNTPAYMENT.PAYMENT_ORIGIN_ID AS PAYMENT_TYPE_ID,
            ACCOUNTPAYMENT.CREATED_DTM,            
            ACCOUNTPAYMENT.ACCOUNT_PAYMENT_TXT AS PAYMENT_TXT,
            ACCOUNTPAYMENT.ALT_ACCOUNT_PAYMENT_MNY AS ALT_PAYMENT_MNY,
            ACCOUNTPAYMENT.ALT_CURRENCY_CODE,
      NULL,
            ACCOUNTPAYMENT.ACCOUNT_PAYMENT_REF,
            B.BILL_SEQ,
            B.BILL_DTM BILL_DATE,
            B.INVOICE_NUM,
           CASE WHEN (ACCOUNTPAYMENT.ACCOUNT_PAYMENT_STATUS = 1 AND B.TRANS_BILLED_TO_DTM > ACCOUNTPAYMENT.ACCOUNT_PAYMENT_DAT) THEN 'BILLED'
            WHEN ACCOUNTPAYMENT.ACCOUNT_PAYMENT_STATUS = 1 THEN 'CREATED'
            WHEN ACCOUNTPAYMENT.ACCOUNT_PAYMENT_STATUS = 0 THEN 'PENDING'
            WHEN ACCOUNTPAYMENT.ACCOUNT_PAYMENT_STATUS = 2 THEN 'CANCELLED'
            WHEN ACCOUNTPAYMENT.ACCOUNT_PAYMENT_STATUS = 3 THEN 'FAILED'
            END  STATUS ,
           ACCOUNTPAYMENT.PHYSICAL_PAYMENT_SEQ,
           ACCOUNTPAYATTRIBUTES.WEB_PORTAL_USER CREATED_BY ,
       ADD_MONTHS(B.BILL_DTM , -1),  -- ADDED FOR TMOGENESIS-21613 : RBM CUSTOM API: QUERY API. START_DAT, START_OF_BILL_DTM
	   PAYMTD.PAYMENT_METHOD_ID,
       PAYMTD.PAYMENT_METHOD_NAME
  FROM GENEVA_ADMIN.ACCOUNTPAYMENT
  LEFT JOIN GENEVA_ADMIN.BILLSUMMARY B
  ON ACCOUNTPAYMENT.ACCOUNT_NUM = B.ACCOUNT_NUM
  AND ACCOUNTPAYMENT.ACCOUNT_PAYMENT_DAT < B.BILL_DTM
  AND ACCOUNTPAYMENT.ACCOUNT_PAYMENT_DAT > B.START_OF_BILL_DTM AND ACCOUNTPAYMENT.ACCOUNT_PAYMENT_STATUS = 1 
  LEFT JOIN GENEVA_ADMIN.ACCOUNTPAYATTRIBUTES
  ON ACCOUNTPAYMENT.ACCOUNT_NUM = ACCOUNTPAYATTRIBUTES.ACCOUNT_NUM
        AND ACCOUNTPAYMENT.ACCOUNT_PAYMENT_SEQ = ACCOUNTPAYATTRIBUTES.ACCOUNT_PAYMENT_SEQ
    JOIN TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
        ON ACCOUNTPAYMENT.ACCOUNT_NUM = TAM.BILLING_ACCT_NBR
        AND TAM.REFACTORED_FLAG ='T'
        AND TRUNC(ACCOUNTPAYMENT.CREATED_DTM) > TAM.REFACTORED_DTM
        AND  ACCOUNTPAYMENT.PAYMENT_ORIGIN_ID = '1'
  LEFT JOIN GENEVA_ADMIN.PHYSICALPAYMENT PHSPAY
  ON ACCOUNTPAYMENT.CUSTOMER_REF=PHSPAY.CUSTOMER_REF
  AND ACCOUNTPAYMENT.PHYSICAL_PAYMENT_SEQ =PHSPAY.PHYSICAL_PAYMENT_SEQ
  LEFT JOIN GENEVA_ADMIN.PAYMENTMETHOD PAYMTD
  ON PHSPAY.PAYMENT_METHOD_ID =PAYMTD.PAYMENT_METHOD_ID
   WITH READ ONLY;


CREATE OR REPLACE PUBLIC SYNONYM TMO_PAYMENT_VIEW FOR TMOBILE_CUSTOM.TMO_PAYMENT_VIEW;

CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_PAYMENT_VIEW FOR TMOBILE_CUSTOM.TMO_PAYMENT_VIEW;

GRANT SELECT ON TMOBILE_CUSTOM.TMO_PAYMENT_VIEW TO UNIF_ADMIN;
