CREATE OR REPLACE VIEW TMOBILE_CUSTOM.TMO_TAX_EXEMPTIONTYPE_VIEW
(exemption_type)
AS SELECT DISTINCT EXEMPTION_TYPE FROM TMOBILE_CUSTOM.TMO_TAX_EXEMPTION  
  WITH READ ONLY;

CREATE OR REPLACE PUBLIC SYNONYM TMO_TAX_EXEMPTIONTYPE_VIEW FOR TMOBILE_CUSTOM.TMO_TAX_EXEMPTIONTYPE_VIEW;

CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_TAX_EXEMPTIONTYPE_VIEW FOR TMOBILE_CUSTOM.TMO_TAX_EXEMPTIONTYPE_VIEW;

GRANT SELECT ON TMOBILE_CUSTOM.TMO_TAX_EXEMPTIONTYPE_VIEW TO UNIF_ADMIN;