BEGIN
  execute immediate 'DROP TABLE TMOBILE_CUSTOM.TMO_INVOICE_USAGE_LINE_ITEM';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
CREATE TABLE "TMOBILE_CUSTOM"."TMO_INVOICE_USAGE_LINE_ITEM" 
   (	"ACCOUNT_NUM" VARCHAR2(20) NOT NULL ENABLE, 
	"EVENT_TYPE_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"TARIFF_ID" NUMBER(9,0), 
	"EVENT_SEQ" NUMBER(9,0) NOT NULL ENABLE, 
	"PRODUCT_SEQ" NUMBER(9,0), 
	"EVENT_SOURCE" VARCHAR2(40) NOT NULL ENABLE, 
	"EVENT_COST_MNY" NUMBER, 
	"CCPC_COMP_CODE" VARCHAR2(40), 
	"CHARGING_RATE" NUMBER, 
	"COST_BAND" VARCHAR2(83), 
	"COST_BAND_DESC" VARCHAR2(40), 
	"EVENT_CLASS" VARCHAR2(40), 
	"ROAMER_FLAG" VARCHAR2(40), 
	"MSISDN_NPANXX" VARCHAR2(6), 
	"ORIG_CELL_SITE_NPANXX" VARCHAR2(40), 
	"DISCOUNT_NAME" VARCHAR2(40), 
	"COST_AIRTIME" NUMBER, 
	"COST_TOLL" NUMBER, 
	"COST_TOTAL" NUMBER, 
	"EVENT_COUNT" NUMBER, 
	"ROUNDED_DURATION" NUMBER, 
	"TOTAL_VOLUME" NUMBER, 
	"DISCOUNTED_BYTES" NUMBER, 
	"TAP_CHARGE" NUMBER, 
	"TECH_TYPE" VARCHAR2(40), 
	"REC_ENTITY" VARCHAR2(40), 
	"FACTOR" NUMBER, 
	"BILLING_TARIFF_NAME" VARCHAR2(40), 
	"TOMS_TLO_ID" VARCHAR2(40), 
	"PPA_TAX_CODE" VARCHAR2(81),
	CONSTRAINT "TMO_INV_USAGELINEITEM_UNIQUE" UNIQUE ("ACCOUNT_NUM", "EVENT_TYPE_ID", "TARIFF_ID", "EVENT_SEQ", "PRODUCT_SEQ", "EVENT_SOURCE", "CCPC_COMP_CODE", "CHARGING_RATE", "COST_BAND", "COST_BAND_DESC", "EVENT_CLASS", "ROAMER_FLAG", "MSISDN_NPANXX", "ORIG_CELL_SITE_NPANXX", "DISCOUNT_NAME", "TECH_TYPE", "REC_ENTITY", "FACTOR", "BILLING_TARIFF_NAME", "TOMS_TLO_ID", "PPA_TAX_CODE")
   ) 
TABLESPACE "USERS" ;
GRANT SELECT ON TMOBILE_CUSTOM.TMO_INVOICE_USAGE_LINE_ITEM TO UNIF_ADMIN;
Grant select, insert, delete on TMOBILE_CUSTOM.TMO_INVOICE_USAGE_LINE_ITEM to geneva_admin, tmorole;

BEGIN
  execute immediate 'DROP TABLE TMOBILE_CUSTOM.TMO_INVOICE_ACTIVESUSPENDDAYS';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
CREATE TABLE "TMOBILE_CUSTOM"."TMO_INVOICE_ACTIVESUSPENDDAYS" 
   (	"CUSTOMER_REF" VARCHAR2(20) NOT NULL ENABLE, 
    "EVENT_SEQ" NUMBER(9,0) NOT NULL ENABLE,
	"PRODUCT_SEQ" NUMBER(9,0) NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(40) NOT NULL ENABLE, 
	"ACTIVEDAYS" NUMBER, 
	"SUSPENDDAYS" NUMBER, 
	"TARIFF_ID" NUMBER(9,0), 
	"SIM" VARCHAR2(40), 
	"TOMS_OBJECT_ID" VARCHAR2(40),
	CONSTRAINT "TMO_INV_ACTIVESUSPENDDAYS_UNIQ" UNIQUE ("CUSTOMER_REF", "EVENT_SEQ", "PRODUCT_SEQ", "MSISDN", "TARIFF_ID", "SIM", "TOMS_OBJECT_ID")
   ) 
TABLESPACE "USERS" ;
GRANT SELECT ON TMOBILE_CUSTOM.TMO_INVOICE_ACTIVESUSPENDDAYS TO UNIF_ADMIN;
Grant select, insert, delete on TMOBILE_CUSTOM.TMO_INVOICE_ACTIVESUSPENDDAYS to geneva_admin, tmorole;

BEGIN
  execute immediate 'DROP TABLE TMOBILE_CUSTOM.TMO_INVOICE_SUB_HSD';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
CREATE TABLE "TMOBILE_CUSTOM"."TMO_INVOICE_SUB_HSD" 
   (	"CUSTOMER_REF" VARCHAR2(20) NOT NULL ENABLE, 
	"PLAN_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20) NOT NULL ENABLE, 
	"SIM" VARCHAR2(20), 
	"PRODUCT_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"PRODUCT_SEQ" NUMBER(9,0) NOT NULL ENABLE, 
	"BASE_TARIFF_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"TARIFF_ID" NUMBER(9,0) NOT NULL ENABLE,
	"BASE_PRODUCT_SEQ" NUMBER(9,0) NOT NULL ENABLE, 
	"BASE_PRODUCT_START_DAT" DATE NOT NULL ENABLE, 
	"PRODUCT_START_DAT" DATE NOT NULL ENABLE, 
	"PRODUCT_STATUS" VARCHAR2(20), 
	"BUCKET_LIMIT" VARCHAR2(40), 
	"EXPIRATION_DATE" VARCHAR2(40), 
	"AUTO_RENEW_FLAG" VARCHAR2(10), 
	"RENEWAL_PERIOD_TYPE" VARCHAR2(10), 
	"RENEWAL_PERIOD_VALUE" VARCHAR2(10), 
	"CREATION_DAT" DATE, 
	"TOMS_OBJECT_ID" VARCHAR2(40),
	 CONSTRAINT "TMO_INVOICE_SUB_HSD_UNIQ" UNIQUE ("CUSTOMER_REF", "PLAN_NAME", "MSISDN", "PRODUCT_NAME", "PRODUCT_ID", "PRODUCT_SEQ", "PRODUCT_START_DAT") 
) 
TABLESPACE "USERS" ;
GRANT SELECT ON TMOBILE_CUSTOM.TMO_INVOICE_SUB_HSD TO UNIF_ADMIN;
Grant select, insert, delete on TMOBILE_CUSTOM.TMO_INVOICE_SUB_HSD to geneva_admin, tmorole;
 
BEGIN
  execute immediate 'alter table TMOBILE_CUSTOM.TMO_MRC_CONFIG add invoice_drilldown_boo varchar2(10)';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/