DROP VIEW TMOBILE_CUSTOM.TMO_SKFCATEGORY_VIEW;

CREATE OR REPLACE FORCE VIEW TMOBILE_CUSTOM.TMO_SKFCATEGORY_VIEW
(
    GL_ACCOUNT, 
    GL_ACCOUNT_DESCRIPTION,
    LINE_ITEM_TEXT
)
AS
   SELECT DISTINCT GL_ACCOUNT, GL_ACCOUNT_DESCRIPTION,LINE_ITEM_TEXT
   FROM TMOBILE_CUSTOM.TMO_GLLINEITEMTEXTMAP map 
   WHERE LENGTH(GL_ACCOUNT)=3
WITH READ ONLY;




CREATE OR REPLACE PUBLIC SYNONYM TMO_SKFCATEGORY_VIEW FOR TMOBILE_CUSTOM.TMO_SKFCATEGORY_VIEW;

CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_SKFCATEGORY_VIEW FOR TMOBILE_CUSTOM.TMO_SKFCATEGORY_VIEW;

GRANT SELECT ON TMOBILE_CUSTOM.TMO_SKFCATEGORY_VIEW TO UNIF_ADMIN;
