DROP VIEW TMOBILE_CUSTOM.TMO_GLACCOUNT_VIEW;

CREATE OR REPLACE FORCE VIEW TMOBILE_CUSTOM.TMO_GLACCOUNT_VIEW
(
    GL_ACCOUNT, 
    GL_ACCOUNT_DESCRIPTION,
    LINE_ITEM_TEXT
)
AS
   SELECT DISTINCT GL_ACCOUNT, GL_ACCOUNT_DESCRIPTION,LINE_ITEM_TEXT
   FROM TMOBILE_CUSTOM.TMO_GLLINEITEMTEXTMAP map
   WHERE CATEGORY_IND='REVENUE' 
     AND LENGTH(GL_ACCOUNT)=8
     AND LINE_ITEM_TEXT = ( SELECT MAX(LINE_ITEM_TEXT)
                                      FROM TMOBILE_CUSTOM.TMO_GLLINEITEMTEXTMAP
                                     WHERE GL_ACCOUNT=MAP.GL_ACCOUNT) 
WITH READ ONLY;


CREATE OR REPLACE PUBLIC SYNONYM TMO_GLACCOUNT_VIEW FOR TMOBILE_CUSTOM.TMO_GLACCOUNT_VIEW;

CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_GLACCOUNT_VIEW FOR TMOBILE_CUSTOM.TMO_GLACCOUNT_VIEW;

GRANT SELECT ON TMOBILE_CUSTOM.TMO_GLACCOUNT_VIEW TO UNIF_ADMIN;
