BEGIN
  execute immediate 'CREATE TABLE TMOBILE_CUSTOM.TMO_POB_TAX_EXEMPTION
(
  TRANSACTION_ID      VARCHAR2(100) not null,
  BILLING_ACCT_NUM    VARCHAR2(50) not null,
  TAX_EXEMPTION_TYPE  VARCHAR2(100) not null,
  STATE_CODE          VARCHAR2(2),
  TAX_TYPE_ID         NUMBER not null,
  RBM_TAX_AUTHORITY   NUMBER not null,
  ACTION              VARCHAR2(100),
  STATUS              VARCHAR2(1000),
  CONSTRAINT  TMO_POB_TAX_PK PRIMARY KEY (TRANSACTION_ID,BILLING_ACCT_NUM,TAX_EXEMPTION_TYPE,STATE_CODE,TAX_TYPE_ID,RBM_TAX_AUTHORITY)
) ';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
GRANT ALL ON TMOBILE_CUSTOM.TMO_POB_TAX_EXEMPTION TO GENEVA_ADMIN,UNIF_ADMIN,GENEVABATCHUSER;


