BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE TMO_POB_ERROR_MESSAGES
(
  ERROR_MESSAGE_ID  NUMBER,
  TRANSACTION_ID   VARCHAR2(40)                NOT NULL,
  ACCOUNT_NUM      VARCHAR2(40)                NOT NULL,
  ERROR_DATE         TIMESTAMP(6)               DEFAULT SYSDATE               NOT NULL,
  ERROR_USER         VARCHAR2(30 BYTE)          DEFAULT USER                  NOT NULL,
  METHOD_NAME        VARCHAR2(100),
  ERROR_MESSAGE1     VARCHAR2(4000 BYTE)
)';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
GRANT ALL ON TMOBILE_CUSTOM.TMO_POB_ERROR_MESSAGES TO GENEVA_ADMIN,UNIF_ADMIN,GENEVABATCHUSER;

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE POB_ERROR_MESSAGE_SEQ
  START WITH 1';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/