DROP VIEW TMOBILE_CUSTOM.TMO_PAYMENT_CHANNELS_VIEW;
CREATE OR REPLACE VIEW TMOBILE_CUSTOM.TMO_PAYMENT_CHANNELS_VIEW
(payment_method_id, payment_method_name, invoicing_co_id) 
AS
SELECT DISTINCT  PAYMENTMETHOD.PAYMENT_METHOD_ID,
            PAYMENTMETHOD.PAYMENT_METHOD_NAME,
            ICOHASPAYMENTMETHOD.INVOICING_CO_ID		
			FROM GENEVA_ADMIN.PAYMENTMETHOD
			JOIN GENEVA_ADMIN.ICOHASPAYMENTMETHOD
			ON PAYMENTMETHOD.PAYMENT_METHOD_ID=ICOHASPAYMENTMETHOD.PAYMENT_METHOD_ID
WITH READ ONLY;
CREATE OR REPLACE PUBLIC SYNONYM TMO_PAYMENT_CHANNELS_VIEW FOR TMOBILE_CUSTOM.TMO_PAYMENT_CHANNELS_VIEW;
CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_PAYMENT_CHANNELS_VIEW FOR TMOBILE_CUSTOM.TMO_PAYMENT_CHANNELS_VIEW;
GRANT SELECT ON TMOBILE_CUSTOM.TMO_PAYMENT_CHANNELS_VIEW TO UNIF_ADMIN;
