DROP VIEW TMOBILE_CUSTOM.TMO_CCPC_VIEW;

CREATE OR REPLACE FORCE VIEW TMOBILE_CUSTOM.TMO_CCPC_VIEW
(
    CCPC_CODE, 
    COMPANY_CODE, 
    CCPC_DESCRIPTION
)
AS
   SELECT DISTINCT CCPC_CODE, COMPANY_CODE, CCPC_DESCRIPTION
   FROM TMOBILE_CUSTOM.TMO_CCPC
WITH READ ONLY;


CREATE OR REPLACE PUBLIC SYNONYM TMO_CCPC_VIEW FOR TMOBILE_CUSTOM.TMO_CCPC_VIEW;

CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_CCPC_VIEW FOR TMOBILE_CUSTOM.TMO_CCPC_VIEW;

GRANT SELECT ON TMOBILE_CUSTOM.TMO_CCPC_VIEW TO UNIF_ADMIN;
