CREATE OR REPLACE  VIEW TMOBILE_CUSTOM.TMO_TAXEXEMPTION_VIEW
(
    CUSTOMER_REF,        
    ACCOUNT_NUM,
    EXTERNAL_TAX_TYPE_ID,        
    STATE_CODE,        
    EXTERNAL_TAX_TYPE_NAME,        
    AUTHORITY,        
    START_DAT,        
    END_DAT ,
    EXEMPTION_TYPE
)
AS
SELECT distinct  ACC.CUSTOMER_REF,        
    UST.ACCOUNT_NUM,
    UST.EXTERNAL_TAX_TYPE_ID,        
    UST.STATE_CODE,        
    EXTEXT.EXTERNAL_TAX_TYPE_NAME,        
    DECODE(EXEMPTION_TAX_AUTHORITY,1 ,'Federal',        
                2   ,'State',        
                3   ,'County',        
                4   ,'City',        
                5   ,'County outside incorporated area',        
                6   ,'Other Municipality',        
                7   ,'County District',        
                8   ,'City District') AUTHORITY,        
    UST.START_DAT,        
    UST.END_DAT,
    AA.EXEMPTION_TYPE
FROM GENEVA_ADMIN.ACCOUNT ACC,
     GENEVA_ADMIN.ACCOUNTATTRIBUTES AA,
     GENEVA_ADMIN.USTACCOUNTHASEXEMPTION UST,        
     GENEVA_ADMIN.USTEXTERNALTAXTYPE EXTEXT
     where AA.ACCOUNT_NUM = ACC.ACCOUNT_NUM
     and UST.ACCOUNT_NUM = AA.ACCOUNT_NUM
     and (UST.END_DAT IS NULL OR UST.END_DAT >= NVL(ACC.LAST_BILL_DTM + 1, INC_MONTHS(ACC.NEXT_BILL_DTM, -1)))
     and UST.EXTERNAL_TAX_TYPE_ID = EXTEXT.EXTERNAL_TAX_TYPE_ID        
     and UST.UST_CHARGE_GROUP_ID = EXTEXT.UST_CHARGE_GROUP_ID 
WITH READ ONLY;

CREATE OR REPLACE PUBLIC SYNONYM TMO_TAXEXEMPTION_VIEW FOR TMOBILE_CUSTOM.TMO_TAXEXEMPTION_VIEW;


CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_TAXEXEMPTION_VIEW FOR TMOBILE_CUSTOM.TMO_TAXEXEMPTION_VIEW;


GRANT SELECT ON TMOBILE_CUSTOM.TMO_TAXEXEMPTION_VIEW TO UNIF_ADMIN;
