CREATE OR REPLACE  VIEW TMOBILE_CUSTOM.TMO_ADJUSTMENT_VIEW
(
    CUSTOMER_REF, 
	ACCOUNT_NUM, 
	ADJUSTMENT_SEQ, 
	ADJUSTMENT_DAT,
	ADJUSTMENT_TYPE_ID,
	ADJUSTMENT_TYPE_NAME,
	ADJUSTMENT_TXT,
    ADJUSTMENT_NET_MNY,
	CREATED_DTM,
	DISPUTE_SEQ,
	ADJUSTMENT_STATUS_ID,    
    ADJUSTMENT_STATUS,
    BUDGET_CENTRE_SEQ,
	BILL_SEQ,
	BILL_DATE,
	CPS_ID, 
	GENEVA_USER_ORA, 
	APPROVED_DTM,
    OUTCOME_DESC,
    RECEIVABLE_CLASS_ID,
    ADJUSTMENT_DEBT_MNY,
	APPLIED_BILL,
	START_BILL_DTM,  -- ADDED for TMOGENESIS-21613 : RBM Custom API: Query API. start_dat, start_of_bill_dtm
	WPSINFO
)
AS
  SELECT  distinct ACCOUNT.CUSTOMER_REF, ADJ.ACCOUNT_NUM , ADJ.ADJUSTMENT_SEQ , ADJ.ADJUSTMENT_DAT, ADJ.ADJUSTMENT_TYPE_ID ,ADJTYPE.ADJUSTMENT_TYPE_NAME || '-' || T.TARIFF_DESC ADJUSTMENT_TYPE_NAME , ADJ.ADJUSTMENT_TXT,
        ADJ.ADJUSTMENT_NET_MNY, ADJ.CREATED_DTM , ADJ.DISPUTE_SEQ, ADJ.ADJUSTMENT_STATUS ADJUSTMENT_STATUS_ID,
        case WHEN DISADJ.BILL_SEQ IS NOT NULL THEN 'BILLED'
        ELSE DECODE(ADJ.ADJUSTMENT_STATUS ,1,'Pending approval', 2, 'Cancelled', 3 ,'Approved', 4, 'Rejected',
        5 ,'Not billed in IRB') END ADJUSTMENT_STATUS ,
        ADJ.BUDGET_CENTRE_SEQ,
        NVL(DISADJ.BILL_SEQ,ADJ.BILL_SEQ) BILL_SEQ ,
        DISADJ.BILL_DATE ,
        ADJ.CPS_ID, ADJ.GENEVA_USER_ORA, DISADJ.BILL_DATE APPROVED_DTM,--ADJ.APPROVED_DTM,
		NVL(SUBSTR(ADJ.OUTCOME_DESC, 0, INSTR(ADJ.OUTCOME_DESC, '|')-1), ADJ.OUTCOME_DESC) OUTCOME_DESC,
    --ADJ.OUTCOME_DESC,
        ADJ.RECEIVABLE_CLASS_ID,
        ADJ.ADJUSTMENT_DEBT_MNY,
        CASE WHEN DISADJ.BILL_SEQ IS NOT NULL THEN 'BILLED'
        ELSE 'UNBILLED'
        END APPLIED_BILL,
    ADD_MONTHS(DISADJ.BILL_DATE , -1),  -- ADDED for TMOGENESIS-21613 : RBM Custom API: Query API. start_dat, start_of_bill_dtm
	ADJATTR.ATTRIBUTE_VALUE AS WPSINFO
     FROM GENEVA_ADMIN.ADJUSTMENT  ADJ
     JOIN GENEVA_ADMIN.PVADJUSTMENTTYPE4 ADJTYPE
     ON ADJ.ADJUSTMENT_TYPE_ID=ADJTYPE.ADJUSTMENT_TYPE_ID
      LEFT JOIN GENEVA_ADMIN.ACCOUNT
     ON ADJ.ACCOUNT_NUM = ACCOUNT.ACCOUNT_NUM
     LEFT JOIN TMOBILE_CUSTOM.TMO_APPLIED_DISPADJ DISADJ
     ON ADJ.ACCOUNT_NUM = DISADJ.ACCOUNT_NUM
        AND ADJ.ADJUSTMENT_SEQ = DISADJ.ADJ_SEQ
     JOIN TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
     ON ADJ.ACCOUNT_NUM = TAM.BILLING_ACCT_NBR
        AND TAM.REFACTORED_FLAG ='T'
        AND ADJ.CREATED_DTM > TAM.REFACTORED_DTM
		LEFT JOIN TMOBILE_CUSTOM.TMO_ADJUSTMENT_ATTRIBUTES ADJATTR
	ON ADJ.ACCOUNT_NUM=ADJATTR.ACCOUNT_NUM
	AND ADJ.ADJUSTMENT_SEQ=ADJATTR.ADJUSTMENT_SEQ
     JOIN TARIFF T
      ON TO_CHAR(T.TARIFF_ID) = TO_CHAR(NVL(regexp_substr (ADJ.OUTCOME_DESC, '[^|]+', 1, 2), ADJ.OUTCOME_DESC)) and T.catalogue_change_id =
                                   (SELECT catalogue_change_id
                                      FROM GENEVA_ADMIN.cataloguechange
                                     WHERE catalogue_status = 3)								 
      where ADJ.ADJUSTMENT_TYPE_ID in (69,23,86)
   UNION
   SELECT  distinct ACCOUNT.CUSTOMER_REF, ADJ.ACCOUNT_NUM , ADJ.ADJUSTMENT_SEQ , ADJ.ADJUSTMENT_DAT, ADJ.ADJUSTMENT_TYPE_ID ,ADJTYPE.ADJUSTMENT_TYPE_NAME, ADJ.ADJUSTMENT_TXT,
        ADJ.ADJUSTMENT_NET_MNY, ADJ.CREATED_DTM , ADJ.DISPUTE_SEQ, ADJ.ADJUSTMENT_STATUS ADJUSTMENT_STATUS_ID,
        case WHEN DISADJ.BILL_SEQ IS NOT NULL THEN 'BILLED'
        ELSE DECODE(ADJ.ADJUSTMENT_STATUS ,1,'Pending approval', 2, 'Cancelled', 3 ,'Approved', 4, 'Rejected',
        5 ,'Not billed in IRB') END ADJUSTMENT_STATUS ,
        ADJ.BUDGET_CENTRE_SEQ,
        NVL(DISADJ.BILL_SEQ,ADJ.BILL_SEQ) BILL_SEQ ,
		DISADJ.BILL_DATE ,
        ADJ.CPS_ID, ADJ.GENEVA_USER_ORA, DISADJ.BILL_DATE APPROVED_DTM,--ADJ.APPROVED_DTM,
        ADJ.OUTCOME_DESC,
        ADJ.RECEIVABLE_CLASS_ID,
        ADJ.ADJUSTMENT_DEBT_MNY,
        CASE WHEN DISADJ.BILL_SEQ IS NOT NULL THEN 'BILLED'
        ELSE 'UNBILLED'
        END APPLIED_BILL ,
    ADD_MONTHS(DISADJ.BILL_DATE , -1),  -- ADDED for TMOGENESIS-21613 : RBM Custom API: Query API. start_dat, start_of_bill_dtm
	ADJATTR.ATTRIBUTE_VALUE AS WPSINFO
     FROM   GENEVA_ADMIN.ADJUSTMENT  ADJ
     JOIN GENEVA_ADMIN.PVADJUSTMENTTYPE4 ADJTYPE
     ON ADJ.ADJUSTMENT_TYPE_ID=ADJTYPE.ADJUSTMENT_TYPE_ID
      LEFT JOIN GENEVA_ADMIN.ACCOUNT
     ON ADJ.ACCOUNT_NUM = ACCOUNT.ACCOUNT_NUM
     LEFT JOIN TMOBILE_CUSTOM.TMO_APPLIED_DISPADJ DISADJ
     ON ADJ.ACCOUNT_NUM = DISADJ.ACCOUNT_NUM
        AND ADJ.ADJUSTMENT_SEQ = DISADJ.ADJ_SEQ
     JOIN TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
     ON ADJ.ACCOUNT_NUM = TAM.BILLING_ACCT_NBR
        AND TAM.REFACTORED_FLAG ='T'
        AND ADJ.CREATED_DTM > TAM.REFACTORED_DTM
	LEFT JOIN TMOBILE_CUSTOM.TMO_ADJUSTMENT_ATTRIBUTES ADJATTR
	ON ADJ.ACCOUNT_NUM=ADJATTR.ACCOUNT_NUM
	AND ADJ.ADJUSTMENT_SEQ=ADJATTR.ADJUSTMENT_SEQ
 where ADJ.ADJUSTMENT_TYPE_ID not in (69,23,86,128)
UNION --New code to handle adjustments with types 69,23,86 created before 11/11 change 
SELECT  distinct ACCOUNT.CUSTOMER_REF, ADJ.ACCOUNT_NUM , ADJ.ADJUSTMENT_SEQ , ADJ.ADJUSTMENT_DAT, ADJ.ADJUSTMENT_TYPE_ID ,ADJTYPE.ADJUSTMENT_TYPE_NAME, ADJ.ADJUSTMENT_TXT,
        ADJ.ADJUSTMENT_NET_MNY, ADJ.CREATED_DTM , ADJ.DISPUTE_SEQ, ADJ.ADJUSTMENT_STATUS ADJUSTMENT_STATUS_ID,
        case WHEN DISADJ.BILL_SEQ IS NOT NULL THEN 'BILLED'
        ELSE DECODE(ADJ.ADJUSTMENT_STATUS ,1,'Pending approval', 2, 'Cancelled', 3 ,'Approved', 4, 'Rejected',
        5 ,'Not billed in IRB') END ADJUSTMENT_STATUS ,
        ADJ.BUDGET_CENTRE_SEQ,
        NVL(DISADJ.BILL_SEQ,ADJ.BILL_SEQ) BILL_SEQ ,
		DISADJ.BILL_DATE ,
        ADJ.CPS_ID, ADJ.GENEVA_USER_ORA, DISADJ.BILL_DATE APPROVED_DTM,--ADJ.APPROVED_DTM,
        ADJ.OUTCOME_DESC,
        ADJ.RECEIVABLE_CLASS_ID,
        ADJ.ADJUSTMENT_DEBT_MNY,
        CASE WHEN DISADJ.BILL_SEQ IS NOT NULL THEN 'BILLED'
        ELSE 'UNBILLED'
        END APPLIED_BILL ,
    ADD_MONTHS(DISADJ.BILL_DATE , -1),  
	ADJATTR.ATTRIBUTE_VALUE AS WPSINFO
     FROM   GENEVA_ADMIN.ADJUSTMENT  ADJ
     JOIN GENEVA_ADMIN.PVADJUSTMENTTYPE4 ADJTYPE
     ON ADJ.ADJUSTMENT_TYPE_ID=ADJTYPE.ADJUSTMENT_TYPE_ID
      LEFT JOIN GENEVA_ADMIN.ACCOUNT
     ON ADJ.ACCOUNT_NUM = ACCOUNT.ACCOUNT_NUM
     LEFT JOIN TMOBILE_CUSTOM.TMO_APPLIED_DISPADJ DISADJ
     ON ADJ.ACCOUNT_NUM = DISADJ.ACCOUNT_NUM
        AND ADJ.ADJUSTMENT_SEQ = DISADJ.ADJ_SEQ
     JOIN TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
     ON ADJ.ACCOUNT_NUM = TAM.BILLING_ACCT_NBR
        AND TAM.REFACTORED_FLAG ='T'
        AND ADJ.CREATED_DTM > TAM.REFACTORED_DTM
	LEFT JOIN TMOBILE_CUSTOM.TMO_ADJUSTMENT_ATTRIBUTES ADJATTR
	ON ADJ.ACCOUNT_NUM=ADJATTR.ACCOUNT_NUM
	AND ADJ.ADJUSTMENT_SEQ=ADJATTR.ADJUSTMENT_SEQ
 where ADJ.ADJUSTMENT_TYPE_ID  in (69,23,86,128)
	AND ADJ.OUTCOME_DESC not like '%|%'  -- Adj Types 69,23,86 will have username|tariffID in outcome_desc
	--AND ADJ.ADJUSTMENT_DAT < to_date('20171111','YYYYMMDD')
WITH READ ONLY;
CREATE OR REPLACE PUBLIC SYNONYM TMO_ADJUSTMENT_VIEW FOR TMOBILE_CUSTOM.TMO_ADJUSTMENT_VIEW;
CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_ADJUSTMENT_VIEW FOR TMOBILE_CUSTOM.TMO_ADJUSTMENT_VIEW;
GRANT SELECT ON TMOBILE_CUSTOM.TMO_ADJUSTMENT_VIEW TO UNIF_ADMIN;
