DROP VIEW TMOBILE_CUSTOM.TMO_PROMOTIONDISCOUNT_VIEW;

CREATE OR REPLACE FORCE VIEW TMOBILE_CUSTOM.TMO_PROMOTIONDISCOUNT_VIEW
(
    GL_ACCOUNT, 
    GL_ACCOUNT_DESCRIPTION,
    LINE_ITEM_TEXT,
    REVENUE_CODE_NAME,
    ID,
    DESCR,
    CREDIT,
    TYPE
)
AS
   SELECT GL.GL_ACCOUNT, 
                 GL.GL_ACCOUNT_DESCRIPTION,
                 GL.LINE_ITEM_TEXT,
                 REV.REVENUE_CODE_NAME,
                 ID,
                 DESCR,
                 CREDIT,
                 TYPE
    FROM TMOBILE_CUSTOM.TMO_GLLINEITEMTEXTMAP GL 
    JOIN TMOBILE_CUSTOM.TMO_GLREVENUECODEMAP REV 
    ON GL.LINE_ITEM_TEXT=REV.LINE_ITEM_TEXT
    JOIN (SELECT EVENT_DISCOUNT_ID as ID,
                         DISCOUNT_NAME     as NAME,
                         DISCOUNT_DESC     as DESCR,
                         'DISCOUNT'        as TYPE
             FROM GENEVA_ADMIN.EVENTDISCOUNT ED 
             JOIN GENEVA_ADMIN.CATALOGUECHANGE CC
             ON ED.CATALOGUE_CHANGE_ID = CC.CATALOGUE_CHANGE_ID 
		AND CATALOGUE_STATUS=3
             UNION ALL 
             SELECT EVENT_TYPE_ID   as ID, 
                         EVENT_TYPE_NAME as NAME,
                         EVENT_TYPE_NAME as DESCR,
                         'CHARGE'        as TYPE 
             FROM GENEVA_ADMIN.EVENTTYPE ET
             WHERE EVENT_TYPE_ID>0) TEST
     ON REVENUE_CODE_NAME = NAME
WITH READ ONLY;


CREATE OR REPLACE PUBLIC SYNONYM TMO_PROMOTIONDISCOUNT_VIEW FOR TMOBILE_CUSTOM.TMO_PROMOTIONDISCOUNT_VIEW;

CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_PROMOTIONDISCOUNT_VIEW FOR TMOBILE_CUSTOM.TMO_PROMOTIONDISCOUNT_VIEW;

GRANT SELECT ON TMOBILE_CUSTOM.TMO_PROMOTIONDISCOUNT_VIEW TO UNIF_ADMIN;
