DROP VIEW TMOBILE_CUSTOM.TMO_GLADJUSTTYPEMAPPING_VIEW;

CREATE OR REPLACE FORCE VIEW TMOBILE_CUSTOM.TMO_GLADJUSTTYPEMAPPING_VIEW
(
   GL_ACCOUNT,
   GL_ACCOUNT_DESCRIPTION,
   LINE_ITEM_TEXT,
   ADJUSTMENT_TYPE_ID, 
   ADJUSTMENT_TYPE_NAME,
   ADJUSTMENT_TYPE_DESC 
)
AS
SELECT TMO_GLLINEITEMTEXTMAP.GL_ACCOUNT,
                 TMO_GLLINEITEMTEXTMAP.GL_ACCOUNT_DESCRIPTION,
                 TMO_GLLINEITEMTEXTMAP.LINE_ITEM_TEXT,
                 ADJ.ADJUSTMENT_TYPE_ID, 
                 ADJ.ADJUSTMENT_TYPE_NAME,
                 ADJ.ADJUSTMENT_TYPE_DESC 
FROM TMOBILE_CUSTOM.TMO_GLLINEITEMTEXTMAP
JOIN TMOBILE_CUSTOM.TMO_GLREVENUECODEMAP 
  ON TMO_GLLINEITEMTEXTMAP.LINE_ITEM_TEXT=TMO_GLREVENUECODEMAP.LINE_ITEM_TEXT
JOIN GENEVA_ADMIN.ADJUSTMENTTYPE ADJ 
  ON TMO_GLREVENUECODEMAP.REVENUE_CODE_NAME=ADJ.ADJUSTMENT_TYPE_NAME
WITH READ ONLY;

CREATE OR REPLACE PUBLIC SYNONYM TMO_GLADJUSTTYPEMAPPING_VIEW FOR TMOBILE_CUSTOM.TMO_GLADJUSTTYPEMAPPING_VIEW;

CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_GLADJUSTTYPEMAPPING_VIEW FOR TMOBILE_CUSTOM.TMO_GLADJUSTTYPEMAPPING_VIEW;

GRANT SELECT ON TMOBILE_CUSTOM.TMO_GLADJUSTTYPEMAPPING_VIEW TO UNIF_ADMIN;
