DECLARE 

v_emp int:=0; 

BEGIN 

  SELECT 1 into v_emp FROM dba_tables where table_name = 'TMO_ACCT_EXEMPTION';  

 --dbms_output.put_line(v_emp);
 

EXCEPTION WHEN NO_DATA_FOUND then
BEGIN 

EXECUTE IMMEDIATE 'CREATE TABLE TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION 
(
  CUSTOMER_REF            VARCHAR2(40) NOT NULL,
  EXEMPTION_TYPE		  VARCHAR2(40) NOT NULL,
  EXEMPTION_START_DATE    DATE NOT NULL,
  EXEMPTION_END_DATE      DATE,
  STATUS         		  VARCHAR2(20) NOT NULL,
  LAST_MODIFIED_DATE	  DATE NOT NULL,
  CREATEDBYUSER			  VARCHAR2(40),
  CONSTRAINT "TMO_ACCT_EXEMPTION_PK" PRIMARY KEY ("CUSTOMER_REF","EXEMPTION_TYPE")
)';

 EXECUTE IMMEDIATE 
'GRANT ALL ON TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION TO UNIF_ADMIN';
 EXECUTE IMMEDIATE 
 'Grant ALL ON TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION TO geneva_admin';
 COMMIT;
END; 

END;
/