CREATE OR REPLACE VIEW TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION_VIEW 
(CUSTOMER_REF, EXEMPTION_TYPE, EXEMPTION_START_DATE, EXEMPTION_END_DATE, STATUS, 
LAST_MODIFIED_DATE)
AS 
  SELECT CUSTOMER_REF, 
         EXEMPTION_TYPE, 
         EXEMPTION_START_DATE, 
         EXEMPTION_END_DATE, 
         STATUS, 
         LAST_MODIFIED_DATE 
  FROM   TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION 
WITH READ ONLY;

CREATE OR REPLACE PUBLIC SYNONYM TMO_ACCT_EXEMPTION_VIEW FOR 
TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION_VIEW;
CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_ACCT_EXEMPTION_VIEW FOR 
TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION_VIEW;
GRANT SELECT ON TMOBILE_CUSTOM.TMO_ACCT_EXEMPTION_VIEW TO UNIF_ADMIN;