DROP VIEW TMOBILE_CUSTOM.TMO_BILLINGHISTORY_VIEW;

CREATE OR REPLACE FORCE VIEW TMOBILE_CUSTOM.TMO_BILLINGHISTORY_VIEW
(
     CUSTOMER_REF,
     ACCOUNT_NUM,
     BILL_SEQ,
     INVOICE_NUM,
     BILL_DTM,
     BILL_STATUS_ID,
     BILL_STATUS,
     EVENTTYPE ,
     EVENTMNY
)
AS
   SELECT 
    CUSTOMER_REF,
    ACCOUNT_NUM,
    BILL_SEQ,
    INVOICE_NUM,
    BILL_DTM,
    BILL_STATUS_ID,
    UPPER(BILL_STATUS) BILL_STATUS,
    EVENTTYPE ,
    EVENTMNY
  FROM (SELECT DISTINCT ACCOUNT.CUSTOMER_REF, BILLSUMMARY.ACCOUNT_NUM, BILLSUMMARY.BILL_SEQ, BILLSUMMARY.INVOICE_NUM, BILLSUMMARY.BILL_DTM, BILLSUMMARY.BILL_STATUS BILL_STATUS_ID, DECODE(BILLSUMMARY.BILL_STATUS,1,  'CREATED') BILL_STATUS  ,'BILL' EVENTTYPE, BILLSUMMARY.INVOICE_NET_MNY+BILLSUMMARY.INVOICE_TAX_MNY EVENTMNY 
    FROM GENEVA_ADMIN.BILLSUMMARY , GENEVA_ADMIN.ACCOUNT,TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM WHERE
   BILLSUMMARY.ACCOUNT_NUM=ACCOUNT.ACCOUNT_NUM 
   AND ACCOUNT.ACCOUNT_NUM = TAM.BILLING_ACCT_NBR
   AND BILLSUMMARY.BILL_DTM > TAM.REFACTORED_DTM
   AND TAM.REFACTORED_FLAG ='T'
   AND BILLSUMMARY.BILL_STATUS=1
    UNION 
    SELECT DISTINCT PYMT.CUSTOMER_REF, PYMT.ACCOUNT_NUM,PYMT.BILL_SEQ,PYMT.INVOICE_NUM,NVL(PYMT.BILL_DATE,PYMT.CREATED_DTM) BILL_DTM,NULL,PYMT.STATUS BILL_STATUS,'PAYMENT' EVENTTYPE,
  PYMT.PAYMENT_MNY EVENTMNY
        FROM TMO_PAYMENT_VIEW PYMT
      WHERE  PYMT.STATUS IN ( 'BILLED', 'CREATED')
    UNION 
    SELECT DISTINCT ADJ.CUSTOMER_REF, ADJ.ACCOUNT_NUM, ADJ.BILL_SEQ,'NULL' INVOICE_NUM,NVL(ADJ.BILL_DATE,ADJ.CREATED_DTM) BILL_DTM,ADJ.ADJUSTMENT_STATUS_ID,ADJ.ADJUSTMENT_STATUS BILL_STATUS, 'ADJUSTMENT' EVENTTYPE, ADJ.ADJUSTMENT_NET_MNY EVENTMNY 
      FROM TMO_ADJUSTMENT_VIEW ADJ
      WHERE ADJ.ADJUSTMENT_STATUS_ID =  1 
     )
   WITH READ ONLY;

CREATE OR REPLACE PUBLIC SYNONYM TMO_BILLINGHISTORY_VIEW FOR TMOBILE_CUSTOM.TMO_BILLINGHISTORY_VIEW;

CREATE OR REPLACE SYNONYM UNIF_ADMIN.TMO_BILLINGHISTORY_VIEW FOR TMOBILE_CUSTOM.TMO_BILLINGHISTORY_VIEW;


GRANT SELECT ON TMOBILE_CUSTOM.TMO_BILLINGHISTORY_VIEW TO UNIF_ADMIN;