BEGIN
  execute immediate 'CREATE TABLE TMOBILE_CUSTOM.TMO_INTL_ROAMING_CHARGES
(
  TRANSACTION_ID      VARCHAR2(100) not null,
  RATING_ACCT_NUM     VARCHAR2(50) not null,
  COUNTRY_NAME        VARCHAR2(250) not null,
  GROUP_NAME          VARCHAR2(250),
  GPRS_CHARGE         NUMBER,
  GPRS_UOM            VARCHAR2(20),
  GPRS_ROUNDING_VALUE NUMBER,
  GPRS_ROUNDING_UOM   VARCHAR2(20),
  SMS_CHARGE          NUMBER,
  VOICE_CHARGE        NUMBER,
  VOICE_UOM           VARCHAR2(20),
  VOICE_ROUNDING_VALUE NUMBER,
  VOICE_ROUNDING_UOM  VARCHAR2(20),
  STATUS              VARCHAR2(2000),
  CONSTRAINT  TMO_INTL_ROAMING_PK PRIMARY KEY (TRANSACTION_ID,RATING_ACCT_NUM,COUNTRY_NAME)
) ';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
GRANT ALL ON TMOBILE_CUSTOM.TMO_INTL_ROAMING_CHARGES TO GENEVA_ADMIN,UNIF_ADMIN,GENEVABATCHUSER;


