GRANT ALL ON TMOBILE_CUSTOM.TMO_ACCT_MAPPING TO UNIF_ADMIN,GENEVA_ADMIN;
GRANT ALL ON TMOBILE_CUSTOM.TMO_EXTRACTINFO TO UNIF_ADMIN,GENEVA_ADMIN;
GRANT ALL ON TMOBILE_CUSTOM.TMO_SUMM_POP_METHODS_80 TO UNIF_ADMIN,GENEVA_ADMIN;
