GRANT SELECT ON GENEVA_ADMIN.LOCSTATE TO public;
GRANT SELECT ON GENEVA_ADMIN.LOCCOUNTY TO public;
GRANT SELECT ON GENEVA_ADMIN.LOCCITY TO public;
GRANT SELECT ON GENEVA_ADMIN.ACCOUNTATTRIBUTES TO public;
GRANT SELECT ON GENEVA_ADMIN.USTACCOUNTHASEXEMPTION TO public;
GRANT SELECT ON GENEVA_ADMIN.ADDRESS TO public;
GRANT ALL  ON GENEVA_ADMIN.GNVTAX TO TMOBILE_CUSTOM;
