GRANT SELECT ON  GENEVA_ADMIN.USTACCOUNTHASEXEMPTION	TO PUBLIC;
GRANT SELECT ON  GENEVA_ADMIN.ACCOUNT					TO PUBLIC;
GRANT SELECT ON  GENEVA_ADMIN.USTEXTERNALTAXTYPE			TO PUBLIC;
GRANT SELECT ON  GENEVA_ADMIN.ACCOUNTATTRIBUTES			TO PUBLIC;
