GRANT SELECT ON  GENEVA_ADMIN.customer					TO PUBLIC;
GRANT SELECT ON  GENEVA_ADMIN.TARIFFELEMENTHASMKTSEGMENT TO PUBLIC;
GRANT SELECT ON  GENEVA_ADMIN.tariff						TO PUBLIC;
GRANT SELECT ON  GENEVA_ADMIN.cataloguechange				TO PUBLIC;
GRANT SELECT ON GENEVA_ADMIN.PVADJUSTMENTTYPE4 TO PUBLIC;
GRANT SELECT ON GENEVA_ADMIN.tariffelementattrdetails TO PUBLIC;
GRANT SELECT ON GENEVA_ADMIN.productpriceattribute TO PUBLIC;
