CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."IMSIPENALTY_VIEW"("IMSI", "BILL_DATE", "ACCOUNT_NUM" ) AS 
SELECT /*+ leading(ACCT) use_hash(ACCT TMO_IMSI_LIST) */ TMO_IMSI_LIST.IMSI,TMO_IMSI_LIST.BILL_DATE, ACCT.BILLING_ACCT_NBR 
FROM TMOBILE_CUSTOM.TMO_IMSI_LIST TMO_IMSI_LIST, TMOBILE_CUSTOM.TMO_ACCT_MAPPING ACCT
WHERE  TMO_IMSI_LIST.ACCOUNT_NUMBER=ACCT.RATING_ACCT_NBR and TMO_IMSI_LIST.PENALITY_FLAG = 1 
WITH READ ONLY;
GRANT SELECT ON TMOBILE_CUSTOM.IMSIPENALTY_VIEW TO UNIF_ADMIN;