--- Usage section view
CREATE OR REPLACE  VIEW TMOBILE_CUSTOM.INVOICESECTIONDETAILSUSAGEVIEW  ("UNIQUE_ID","PARTNER_NAME","PARTNER_TYPE" , "DESCRIPTION", "EVENT_SUMMARY_ID","BILL_SEQ","ACCOUNT_NUM","COST_BAND_DESC","EVENT_CLASS", "BILLING_TARIFF_NAME","TLO_OBJECT_ID","UNIT_PRICE","DISCOUNT_NAME","TECH_TYPE","CDR_TYPE", "PLAN", "TYPE","QUANTITY", "UNIT_TYPE","TOTAL_AMOUNT","ORDER_NUM" ) AS
SELECT
  '1-' || TOP.SEQ || '-0000-' || BES.GROUP_ATTR_8 UNIQUE_ID
  ,TAM.CUSTOMER_NAME PARTNER_NAME
  ,TAM.CUST_TYPE PARTNER_TYPE
  ,(CASE WHEN BES.EVENT_SUMMARY_ID = 79 AND BES.GROUP_ATTR_13 != 'UNIT' AND BES.GROUP_ATTR_4 = 0 AND BES.GROUP_ATTR_7 = 'Standard' THEN  'SMS - Free'
         WHEN BES.EVENT_SUMMARY_ID = 79 AND BES.GROUP_ATTR_13 != 'UNIT' AND BES.GROUP_ATTR_4 = 0 AND BES.GROUP_ATTR_7 = 'Roaming'  THEN  'SMS - Free - Roaming'
         WHEN BES.EVENT_SUMMARY_ID = 79 AND BES.GROUP_ATTR_6 = 'SMS - Admin' THEN  'SMS Shortcode'
       WHEN BES.EVENT_SUMMARY_ID = 80 and BES.GROUP_ATTR_7 = 'Standard WiFi' THEN 'GPRS - Standard WiFi'
       WHEN BES.EVENT_SUMMARY_ID in (87,88,89) THEN
           CASE WHEN BES.GROUP_ATTR_6 = 'Standard ChargeBack ILD' THEN TIO.DESCRIPTION
       WHEN BES.GROUP_ATTR_14 IS NOT NULL THEN 
          CASE WHEN BES.GROUP_ATTR_14 IN ('T1','T2','T3') THEN  TIO.DESCRIPTION
             WHEN BES.GROUP_ATTR_14 = 'P' THEN TIO.DESCRIPTION || ' - Penalty'
                     WHEN BES.GROUP_ATTR_14 = 'F' THEN TIO.DESCRIPTION || ' - Discounted'
           WHEN BES.GROUP_ATTR_14 = 'C' THEN TIO.DESCRIPTION || ' - Charged'
        END
       WHEN BES.account_num='ACC000171'  AND  BES.GROUP_ATTR_13 != 'UNIT' AND BES.GROUP_ATTR_4 != 0 THEN TIO.DESCRIPTION || ' - Penalty'
           WHEN  BES.GROUP_ATTR_13 != 'UNIT' AND  BES.GROUP_ATTR_4 = 0 THEN TIO.DESCRIPTION || ' - Discounted'
             WHEN  BES.GROUP_ATTR_13 != 'UNIT'  THEN TIO.DESCRIPTION || ' - Charged'
           ELSE TIO.DESCRIPTION END
   ELSE NVL(TIO.DESCRIPTION, CASE WHEN BES.EVENT_SUMMARY_ID = 82 then 'Airtime - Intl Roaming - ' || trim(Substr(BES.GROUP_ATTR_6,  Instr(BES.GROUP_ATTR_6, ' - ')+3))
                                  WHEN BES.EVENT_SUMMARY_ID = 83 then 'SMS - International-'|| trim(Substr(BES.GROUP_ATTR_6,  Instr(BES.GROUP_ATTR_6, '-')+3))
                                  WHEN BES.EVENT_SUMMARY_ID = 84 then 'GPRS - Intl Roaming - '|| trim(Substr(BES.GROUP_ATTR_6,  Instr(BES.GROUP_ATTR_6, ' - ')+3))
                                  ELSE BES.GROUP_ATTR_6 ||' - '||BES.GROUP_ATTR_7 END)  END)DESCRIPTION
  ,BES.EVENT_SUMMARY_ID EVENT_SUMMARY_ID
  ,BS.BILL_SEQ
  ,BILLING_ACCT_NBR ACCOUNT_NUM
  ,CASE WHEN TIO.EVENT_SUMMARY_ID = 79 AND TIO.Cost_Band_Desc = 'NULL'  THEN  'SMS'
   ELSE NVL(TIO.Cost_Band_Desc,BES.GROUP_ATTR_6) END COST_BAND_DESC
  , NVL(TIO.EVENT_CLASS_NAME,BES.GROUP_ATTR_7) EVENT_CLASS
  ,BES.GROUP_ATTR_3 BILLING_TARIFF_NAME
  ,BES.GROUP_ATTR_5 TLO_OBJECT_ID
  ,(CASE WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'STANDARD%' AND UPPER(BES.GROUP_ATTR_11) = 'FREE' AND BES.EVENT_SUMMARY_ID = 80
              THEN 0
         WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'ROAMING%' AND UPPER(BES.GROUP_ATTR_11) = 'TIER1' AND BES.EVENT_SUMMARY_ID = 80
          THEN 0
     WHEN BES.EVENT_SUMMARY_ID IN (80,84,78,82,89,87,88) 
              THEN TO_NUMBER(BES.GROUP_ATTR_4)/1000000
         ELSE TO_NUMBER(BES.GROUP_ATTR_4)/10000
    END) UNIT_PRICE
  ,BES.GROUP_ATTR_11 DISCOUNT_NAME
  ,DECODE(BES.GROUP_ATTR_9,'UNKNOWN','',BES.GROUP_ATTR_9) TECH_TYPE
  ,DECODE(TAM.UF_FORMAT,'VAR','M2M','MVNO') CDR_TYPE
  ,(CASE 
    WHEN BES.GROUP_ATTR_13 = 'UNIT' AND BES.GROUP_ATTR_4 = 0 THEN PLAN.PLAN_NAME ||'(Included)'
  WHEN BES.GROUP_ATTR_13 = 'UNIT' AND BES.GROUP_ATTR_4 != 0 THEN PLAN.PLAN_NAME ||'(Overage)'
  WHEN BES.GROUP_ATTR_14 IN ('T1','T2','T3') THEN BES.GROUP_ATTR_3 || '-Plan' || substr(BES.GROUP_ATTR_14,-1,1)
    WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'STANDARD%' AND UPPER(BES.GROUP_ATTR_11) = 'FREE' AND BES.EVENT_SUMMARY_ID = 80 AND BES.GROUP_ATTR_4 != 0
        THEN PLAN.PLAN_NAME ||' - '||'Incl.'
    WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'STANDARD%' AND UPPER(BES.GROUP_ATTR_11) = 'HOME' AND BES.EVENT_SUMMARY_ID = 80 AND BES.GROUP_ATTR_4 != 0
        THEN PLAN.PLAN_NAME ||' - '||'Not-Incl.'
    WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'ROAMING%' AND UPPER(BES.GROUP_ATTR_11) = 'TIER1' AND BES.EVENT_SUMMARY_ID = 80 AND BES.GROUP_ATTR_4 != 0
        THEN PLAN.PLAN_NAME ||' - '||'Incl.'
    WHEN BILLING_ACCT_NBR = 'ACC000159' AND UPPER(BES.GROUP_ATTR_7) like 'ROAMING%' AND UPPER(BES.GROUP_ATTR_11) = 'TIER2' AND BES.EVENT_SUMMARY_ID = 80 AND BES.GROUP_ATTR_4 != 0
        THEN PLAN.PLAN_NAME ||' - '||'Not-Incl.'
    ELSE PLAN.PLAN_NAME END) PLAN
  ,(CASE
       WHEN BES.GROUP_ATTR_8 LIKE '1-%' THEN SUBSTR(BES.GROUP_ATTR_8,3,3)
       ELSE BES.GROUP_ATTR_8
     END) TYPE
  ,SUM(CASE WHEN BES.GROUP_ATTR_13 = 'UNIT' THEN 
      CASE WHEN BES.EVENT_SUMMARY_ID in (78,80,82,84,87,89) THEN TO_NUMBER(BES.SUM_ATTR_3)
      ELSE TO_NUMBER(BES.SUM_ATTR_1) END
    WHEN BES.EVENT_SUMMARY_ID = 80 OR BES.EVENT_SUMMARY_ID = 84 THEN CEIL((TO_NUMBER(BES.SUM_ATTR_3)/1048576)*10000)/10000
    WHEN BES.EVENT_SUMMARY_ID = 78 OR BES.EVENT_SUMMARY_ID = 82 OR BES.EVENT_SUMMARY_ID = 87 THEN TO_NUMBER(BES.SUM_ATTR_3)/60
    WHEN BES.EVENT_SUMMARY_ID = 89 THEN 
    CASE WHEN (BILLING_ACCT_NBR='ACC000141' AND BES.GROUP_ATTR_7 ='High')
      THEN CEIL((TO_NUMBER(BES.SUM_ATTR_3)/1048576)*10000/10000)
    ELSE CEIL((TO_NUMBER(BES.SUM_ATTR_3)/1048576)*10000)/10000
    END
    ELSE TO_NUMBER(BES.SUM_ATTR_1)
  END ) QUANTITY
  ,BES.GROUP_ATTR_13 UNIT_TYPE
  ,SUM( CASE WHEN BES.EVENT_SUMMARY_ID = 78
             THEN TO_NUMBER(BES.SUM_ATTR_4)
     ELSE TO_NUMBER(BES.SUM_ATTR_2) END)/10000 TOTAL_AMOUNT
  ,NVL(TIO.ORDER_NUM, CASE WHEN BES.EVENT_SUMMARY_ID = 82 then 200
                                  WHEN BES.EVENT_SUMMARY_ID = 83 then 375
                                  WHEN BES.EVENT_SUMMARY_ID = 84 then 600
                        END)  ORDER_NUM
  FROM
      TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
      ,GENEVA_ADMIN.BILLSUMMARY BS
      ,GENEVA_ADMIN.PVBILLEVENTSUMMARY6 BES
      ,GENEVA_ADMIN.PVEVENTSUMMARY2 ES
      ,TMOBILE_CUSTOM.TMO_OFFERPLANID_80 TOP
      ,TMOBILE_CUSTOM.TMO_INVOICE_DESC_ORDERING  TIO
    ,TMOBILE_CUSTOM.GENPLANNAMEMAPVIEW  PLAN
      WHERE TAM.REFACTORED_FLAG = 'T'
      AND TAM.BILLING_ACCT_NBR = BS.ACCOUNT_NUM
    AND TOP.RATING_ACCT_NBR = TAM.RATING_ACCT_NBR
    AND TOP.TOMS_OBJECT_ID = BES.GROUP_ATTR_5
    AND TOP.TARIFF_ID = PLAN.RBTARIFFID
      AND BS.BILL_STATUS IN (1,7,8)
      AND BS.BILL_VERSION = (SELECT MAX(BILL_VERSION) FROM GENEVA_ADMIN.BILLSUMMARY B WHERE B.ACCOUNT_NUM=BS.ACCOUNT_NUM AND B.BILL_SEQ=BS.BILL_SEQ  AND BS.BILL_STATUS IN (1,7,8))
      AND BS.ACCOUNT_NUM  = BES.ACCOUNT_NUM
      AND BS.BILL_SEQ  = BES.BILL_SEQ
      AND BES.EVENT_SUMMARY_ID = ES.EVENT_SUMMARY_ID
      AND ((BES.GROUP_ATTR_3 NOT LIKE '%IOT%' AND PLAN.TARIFF_NAME = BES.GROUP_ATTR_3)
      OR (BES.GROUP_ATTR_3 LIKE '%IOT%' AND (PLAN.TARIFF_NAME = BES.GROUP_ATTR_3 OR PLAN.TARIFF_DESC  = BES.GROUP_ATTR_3 OR (PLAN.TARIFF_DESC = SUBSTR(BES.GROUP_ATTR_3,0,LENGTH(BES.GROUP_ATTR_3)- 4))
      OR (PLAN.TARIFF_DESC = SUBSTR(BES.GROUP_ATTR_3,0,LENGTH(BES.GROUP_ATTR_3)- 3) ))))
    AND PLAN.TOMSOBJID = BES.GROUP_ATTR_5
    AND TAM.BILLING_EVENT_SRC = BES.GROUP_ATTR_1
      AND BES.EVENT_SUMMARY_ID = ES.EVENT_SUMMARY_ID
      AND ES.EVENT_SUMMARY_ID IN (78,79,80,81,82,83,84,89,87,88)
      AND BES.GROUP_ATTR_6  LIKE  TIO.COST_BAND_DESC(+)
      AND BES.GROUP_ATTR_7  LIKE  TIO.EVENT_CLASS_NAME(+)
      AND BES.EVENT_SUMMARY_ID=TIO.EVENT_SUMMARY_ID(+)
    AND (BES.GROUP_ATTR_12 IS NULL OR UPPER(BES.GROUP_ATTR_12) = 'NULL')
GROUP BY
  BILLING_ACCT_NBR
  ,(CASE WHEN BES.EVENT_SUMMARY_ID = 79 AND BES.GROUP_ATTR_13 != 'UNIT' AND BES.GROUP_ATTR_4 = 0 AND BES.GROUP_ATTR_7 = 'Standard' THEN  'SMS - Free'
         WHEN BES.EVENT_SUMMARY_ID = 79 AND BES.GROUP_ATTR_13 != 'UNIT' AND BES.GROUP_ATTR_4 = 0 AND BES.GROUP_ATTR_7 = 'Roaming'  THEN  'SMS - Free - Roaming'
         WHEN BES.EVENT_SUMMARY_ID = 79 AND BES.GROUP_ATTR_6 = 'SMS - Admin' THEN  'SMS Shortcode'
       WHEN BES.EVENT_SUMMARY_ID = 80 and BES.GROUP_ATTR_7 = 'Standard WiFi' THEN 'GPRS - Standard WiFi'
       WHEN BES.EVENT_SUMMARY_ID in (87,88,89) THEN
           CASE  WHEN BES.GROUP_ATTR_6 = 'Standard ChargeBack ILD' THEN TIO.DESCRIPTION
        WHEN BES.GROUP_ATTR_14 IS NOT NULL THEN 
          CASE WHEN BES.GROUP_ATTR_14 in ('T1','T2','T3') THEN  TIO.DESCRIPTION
             WHEN BES.GROUP_ATTR_14 = 'P' THEN TIO.DESCRIPTION || ' - Penalty'
                     WHEN BES.GROUP_ATTR_14 = 'F' THEN TIO.DESCRIPTION || ' - Discounted'
           WHEN BES.GROUP_ATTR_14 = 'C' THEN TIO.DESCRIPTION || ' - Charged'
        END
       WHEN BES.account_num='ACC000171'  AND  BES.GROUP_ATTR_13 != 'UNIT' AND BES.GROUP_ATTR_4 != 0 THEN TIO.DESCRIPTION || ' - Penalty'
           WHEN  BES.GROUP_ATTR_13 != 'UNIT' AND  BES.GROUP_ATTR_4 = 0 THEN TIO.DESCRIPTION || ' - Discounted'
             WHEN  BES.GROUP_ATTR_13 != 'UNIT'  THEN TIO.DESCRIPTION || ' - Charged'
           ELSE TIO.DESCRIPTION END
   ELSE NVL(TIO.DESCRIPTION, CASE WHEN BES.EVENT_SUMMARY_ID = 82 then 'Airtime - Intl Roaming - ' || trim(Substr(BES.GROUP_ATTR_6,  Instr(BES.GROUP_ATTR_6, ' - ')+3))
                                  WHEN BES.EVENT_SUMMARY_ID = 83 then 'SMS - International-'|| trim(Substr(BES.GROUP_ATTR_6,  Instr(BES.GROUP_ATTR_6, '-')+3))
                                  WHEN BES.EVENT_SUMMARY_ID = 84 then 'GPRS - Intl Roaming - '|| trim(Substr(BES.GROUP_ATTR_6,  Instr(BES.GROUP_ATTR_6, ' - ')+3))
                                  ELSE BES.GROUP_ATTR_6 ||' - '||BES.GROUP_ATTR_7 END)  END)
  ,ES.EVENT_TYPE_ID
  ,CASE WHEN TIO.EVENT_SUMMARY_ID = 79 AND TIO.Cost_Band_Desc = 'NULL'  THEN  'SMS'
   ELSE NVL(TIO.Cost_Band_Desc,BES.GROUP_ATTR_6) END
  ,NVL(TIO.EVENT_CLASS_NAME,BES.GROUP_ATTR_7)
  ,BES.GROUP_ATTR_3
  ,(CASE WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'STANDARD%' AND UPPER(BES.GROUP_ATTR_11) = 'FREE' AND BES.EVENT_SUMMARY_ID = 80
              THEN 0
         WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'ROAMING%' AND UPPER(BES.GROUP_ATTR_11) = 'TIER1' AND BES.EVENT_SUMMARY_ID = 80
          THEN 0
     WHEN BES.EVENT_SUMMARY_ID IN (80,84,78,82,89,87,88)
              THEN TO_NUMBER(BES.GROUP_ATTR_4)/1000000
         ELSE TO_NUMBER(BES.GROUP_ATTR_4)/10000
    END)
  ,BES.GROUP_ATTR_5
  ,BES.GROUP_ATTR_11
  ,BES.GROUP_ATTR_9
  ,DECODE(TAM.UF_FORMAT,'VAR','M2M','MVNO')
  ,(CASE 
  WHEN BES.GROUP_ATTR_13 = 'UNIT' AND BES.GROUP_ATTR_4 = 0 THEN PLAN.PLAN_NAME ||'(Included)'
  WHEN BES.GROUP_ATTR_13 = 'UNIT' AND BES.GROUP_ATTR_4 != 0 THEN PLAN.PLAN_NAME ||'(Overage)'
  WHEN BES.GROUP_ATTR_14 IN ('T1','T2','T3') THEN BES.GROUP_ATTR_3 || '-Plan' || substr(BES.GROUP_ATTR_14,-1,1)
    WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'STANDARD%' AND UPPER(BES.GROUP_ATTR_11) = 'FREE' AND BES.EVENT_SUMMARY_ID = 80 AND BES.GROUP_ATTR_4 != 0
        THEN PLAN.PLAN_NAME ||' - '||'Incl.'
    WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'STANDARD%' AND UPPER(BES.GROUP_ATTR_11) = 'HOME' AND BES.EVENT_SUMMARY_ID = 80 AND BES.GROUP_ATTR_4 != 0
        THEN PLAN.PLAN_NAME ||' - '||'Not-Incl.'
    WHEN UPPER(TAM.UF_FORMAT) = 'VAR' AND UPPER(BES.GROUP_ATTR_7) like 'ROAMING%' AND UPPER(BES.GROUP_ATTR_11) = 'TIER1' AND BES.EVENT_SUMMARY_ID = 80 AND BES.GROUP_ATTR_4 != 0
        THEN PLAN.PLAN_NAME ||' - '||'Incl.'
    WHEN BILLING_ACCT_NBR = 'ACC000159' AND UPPER(BES.GROUP_ATTR_7) like 'ROAMING%' AND UPPER(BES.GROUP_ATTR_11) = 'TIER2' AND BES.EVENT_SUMMARY_ID = 80 AND BES.GROUP_ATTR_4 != 0
        THEN PLAN.PLAN_NAME ||' - '||'Not-Incl.'
    ELSE PLAN.PLAN_NAME END)
  ,DECODE(BES.GROUP_ATTR_9,'UNKNOWN','',BES.GROUP_ATTR_9)
  ,BES.GROUP_ATTR_8
  ,BES.GROUP_ATTR_13
  ,TAM.CUSTOMER_NAME
  ,TAM.CUST_TYPE  
  ,BES.EVENT_SUMMARY_ID
  ,BS.BILL_SEQ
  ,NVL(TIO.ORDER_NUM, CASE WHEN BES.EVENT_SUMMARY_ID = 82 then 200
                                  WHEN BES.EVENT_SUMMARY_ID = 83 then 375
                                  WHEN BES.EVENT_SUMMARY_ID = 84 then 600
                        END)
  ,'1-' || TOP.SEQ || '-0000-' || BES.GROUP_ATTR_8
 UNION
SELECT
'1-' || TOP.SEQ || '-0000-' || BES.GROUP_ATTR_8 UNIQUE_ID
,TAM.CUSTOMER_NAME PARTNER_NAME
  ,TAM.CUST_TYPE PARTNER_TYPE
  , (BES.GROUP_ATTR_6 || ' AirTime ' ||' - '||BES.GROUP_ATTR_7) DESCRIPTION
  ,BES.EVENT_SUMMARY_ID EVENT_SUMMARY_ID
  ,BS.BILL_SEQ
  ,BILLING_ACCT_NBR ACCOUNT_NUM
  , BES.GROUP_ATTR_6 COST_BAND_DESC
  , BES.GROUP_ATTR_7 EVENT_CLASS
  ,BES.GROUP_ATTR_3 BILLING_TARIFF_NAME            
  ,BES.GROUP_ATTR_5 TLO_OBJECT_ID
  ,(TO_NUMBER(SUM_ATTR_4)/10000)/(TO_NUMBER(SUM_ATTR_3)/60) UNIT_PRICE
  ,BES.GROUP_ATTR_11 DISCOUNT_NAME                  
  ,DECODE(BES.GROUP_ATTR_9,'UNKNOWN','',BES.GROUP_ATTR_9) TECH_TYPE
  ,DECODE(TAM.UF_FORMAT,'VAR','M2M','MVNO') CDR_TYPE
  ,PLAN.PLAN_NAME PLAN
  ,(CASE 
       WHEN BES.GROUP_ATTR_8 LIKE '1-%' THEN SUBSTR(BES.GROUP_ATTR_8,3,3)
       ELSE BES.GROUP_ATTR_8 
     END) TYPE
  ,SUM(TO_NUMBER(BES.SUM_ATTR_3))/60 QUANTITY
  ,'MOU' UNIT_TYPE
  ,SUM(TO_NUMBER(BES.SUM_ATTR_4))/10000 TOTAL_AMOUNT
  ,151
  FROM
      TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
      ,GENEVA_ADMIN.BILLSUMMARY BS
      ,GENEVA_ADMIN.PVBILLEVENTSUMMARY6 BES
      ,TMOBILE_CUSTOM.TMO_OFFERPLANID_80 TOP
    ,TMOBILE_CUSTOM.GENPLANNAMEMAPVIEW  PLAN
      WHERE TAM.REFACTORED_FLAG = 'T'
      AND TAM.BILLING_ACCT_NBR = BS.ACCOUNT_NUM
    AND TOP.RATING_ACCT_NBR = TAM.RATING_ACCT_NBR
    AND TOP.TOMS_OBJECT_ID = BES.GROUP_ATTR_5
    AND TOP.TARIFF_ID = PLAN.RBTARIFFID
      AND BS.BILL_STATUS IN (1,7,8)
      AND BS.BILL_VERSION = (SELECT MAX(BILL_VERSION) FROM GENEVA_ADMIN.BILLSUMMARY B WHERE B.ACCOUNT_NUM=BS.ACCOUNT_NUM AND B.BILL_SEQ=BS.BILL_SEQ  AND BS.BILL_STATUS IN (1,7,8))
      AND BS.ACCOUNT_NUM  = BES.ACCOUNT_NUM
      AND BS.BILL_SEQ  = BES.BILL_SEQ      
      AND ((BES.GROUP_ATTR_3 NOT LIKE '%IOT%' AND PLAN.TARIFF_NAME = BES.GROUP_ATTR_3) 
      OR (BES.GROUP_ATTR_3 LIKE '%IOT%' AND (PLAN.TARIFF_NAME = BES.GROUP_ATTR_3 OR PLAN.TARIFF_DESC  = BES.GROUP_ATTR_3 OR (PLAN.TARIFF_DESC = SUBSTR(BES.GROUP_ATTR_3,0,LENGTH(BES.GROUP_ATTR_3)- 4)) 
      OR (PLAN.TARIFF_DESC = SUBSTR(BES.GROUP_ATTR_3,0,LENGTH(BES.GROUP_ATTR_3)- 3) ))))
    AND PLAN.TOMSOBJID = BES.GROUP_ATTR_5
    AND TAM.BILLING_EVENT_SRC = BES.GROUP_ATTR_1
      AND BES.EVENT_SUMMARY_ID IN (92)
    AND BES.SUM_ATTR_4 !=0
GROUP BY
  TAM.CUSTOMER_NAME 
  ,TAM.CUST_TYPE 
  , (BES.GROUP_ATTR_6 || ' AirTime ' ||' - '||BES.GROUP_ATTR_7) 
  ,BES.EVENT_SUMMARY_ID 
  ,BS.BILL_SEQ
  ,BILLING_ACCT_NBR 
  , BES.GROUP_ATTR_6 
  , BES.GROUP_ATTR_7 
  ,BES.GROUP_ATTR_3             
  ,BES.GROUP_ATTR_5 
 ,(TO_NUMBER(SUM_ATTR_4)/10000)/(TO_NUMBER(SUM_ATTR_3)/60)
  ,BES.GROUP_ATTR_11                   
  ,DECODE(BES.GROUP_ATTR_9,'UNKNOWN','',BES.GROUP_ATTR_9) 
  ,DECODE(TAM.UF_FORMAT,'VAR','M2M','MVNO') 
  ,PLAN.PLAN_NAME 
  ,(CASE 
       WHEN BES.GROUP_ATTR_8 LIKE '1-%' THEN SUBSTR(BES.GROUP_ATTR_8,3,3)
       ELSE BES.GROUP_ATTR_8 
     END)
  ,'1-' || TOP.SEQ || '-0000-' || BES.GROUP_ATTR_8
UNION
  SELECT
'1-' || TOP.SEQ || '-0'|| ED.EVENT_DISCOUNT_ID || '-'  ||BES.GROUP_ATTR_8 UNIQUE_ID
   ,TAM.CUSTOMER_NAME PARTNER_NAME
  ,TAM.CUST_TYPE PARTNER_TYPE
  ,NVL(TIO.DESCRIPTION, BES.GROUP_ATTR_6 ||' - '||BES.GROUP_ATTR_7) DESCRIPTION
  ,BES.EVENT_SUMMARY_ID EVENT_SUMMARY_ID
  ,BS.BILL_SEQ
  ,BILLING_ACCT_NBR ACCOUNT_NUM
  , NVL(TIO.Cost_Band_Desc,BES.GROUP_ATTR_6) COST_BAND_DESC
  , NVL(TIO.EVENT_CLASS_NAME,BES.GROUP_ATTR_7) EVENT_CLASS
  ,BES.GROUP_ATTR_3 BILLING_TARIFF_NAME            
  ,BES.GROUP_ATTR_5 TLO_OBJECT_ID
  , TO_NUMBER(BES.GROUP_ATTR_4)/1000000 - TO_NUMBER(EDS.DISCOUNT_MNY)/10000 UNIT_PRICE 
  ,ED.DISCOUNT_NAME  DISCOUNT_NAME                 
  ,DECODE(BES.GROUP_ATTR_9,'UNKNOWN','',BES.GROUP_ATTR_9) TECH_TYPE
  ,DECODE(TAM.UF_FORMAT,'VAR','M2M','MVNO') CDR_TYPE
  ,PLAN.PLAN_NAME ||'-'|| ED.DISCOUNT_NAME  PLAN
  ,(CASE 
       WHEN BES.GROUP_ATTR_8 LIKE '1-%' THEN SUBSTR(BES.GROUP_ATTR_8,3,3)
       ELSE BES.GROUP_ATTR_8 
     END) TYPE
  ,SUM(CASE WHEN BES.EVENT_SUMMARY_ID = 89 THEN (CEIL((TO_NUMBER(BES.SUM_ATTR_3)/1048576)*10000)/10000)
        WHEN BES.EVENT_SUMMARY_ID = 87 then TO_NUMBER(BES.SUM_ATTR_3)/60
        WHEN BES.EVENT_SUMMARY_ID = 88 then TO_NUMBER(BES.SUM_ATTR_1)
   END) QUANTITY
  ,BES.GROUP_ATTR_13  UNIT_TYPE
  --,SUM(TO_NUMBER(BES.SUM_ATTR_2))/10000 TOTAL_AMOUNT
  ,SUM(TO_NUMBER(BES.SUM_ATTR_2))/10000 TOTAL_AMOUNT
  ,TIO.ORDER_NUM ORDER_NUM
  FROM
      TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
      ,GENEVA_ADMIN.BILLSUMMARY BS
      ,GENEVA_ADMIN.PVBILLEVENTSUMMARY6 BES
      ,GENEVA_ADMIN.PVEVENTSUMMARY2 ES
      ,TMOBILE_CUSTOM.TMO_OFFERPLANID_80 TOP
      ,TMOBILE_CUSTOM.TMO_INVOICE_DESC_ORDERING  TIO
    ,TMOBILE_CUSTOM.GENPLANNAMEMAPVIEW  PLAN
    ,GENEVA_ADMIN.EVENTDISCOUNT    ED
    , GENEVA_ADMIN.EVENTDISCOUNTSTEP EDS
      WHERE TAM.REFACTORED_FLAG = 'T'
      AND TAM.BILLING_ACCT_NBR = BS.ACCOUNT_NUM
    AND TOP.RATING_ACCT_NBR = TAM.RATING_ACCT_NBR
    AND TOP.TOMS_OBJECT_ID = BES.GROUP_ATTR_5
    AND TOP.TARIFF_ID = PLAN.RBTARIFFID
      AND BS.BILL_STATUS IN (1,7,8)
      AND BS.BILL_VERSION = (SELECT MAX(BILL_VERSION) FROM GENEVA_ADMIN.BILLSUMMARY B WHERE B.ACCOUNT_NUM=BS.ACCOUNT_NUM AND B.BILL_SEQ=BS.BILL_SEQ  AND BS.BILL_STATUS IN (1,7,8))
      AND BS.ACCOUNT_NUM  = BES.ACCOUNT_NUM
      AND BS.BILL_SEQ  = BES.BILL_SEQ
      AND BES.EVENT_SUMMARY_ID = ES.EVENT_SUMMARY_ID        
      AND ((BES.GROUP_ATTR_3 NOT LIKE '%IOT%' AND PLAN.TARIFF_NAME = BES.GROUP_ATTR_3) 
      OR (BES.GROUP_ATTR_3 LIKE '%IOT%' AND (PLAN.TARIFF_NAME = BES.GROUP_ATTR_3 OR PLAN.TARIFF_DESC  = BES.GROUP_ATTR_3 OR (PLAN.TARIFF_DESC = SUBSTR(BES.GROUP_ATTR_3,0,LENGTH(BES.GROUP_ATTR_3)- 4)) 
      OR (PLAN.TARIFF_DESC = SUBSTR(BES.GROUP_ATTR_3,0,LENGTH(BES.GROUP_ATTR_3)- 3) ))))
    AND PLAN.TOMSOBJID = BES.GROUP_ATTR_5
    AND TAM.BILLING_EVENT_SRC = BES.GROUP_ATTR_1
      AND BES.EVENT_SUMMARY_ID = ES.EVENT_SUMMARY_ID
      AND ES.EVENT_SUMMARY_ID IN (89,87,88)
      AND BES.GROUP_ATTR_6  LIKE  TIO.COST_BAND_DESC(+)
      AND BES.GROUP_ATTR_7  LIKE  TIO.EVENT_CLASS_NAME(+)
      AND BES.EVENT_SUMMARY_ID=TIO.EVENT_SUMMARY_ID(+)
    AND TO_NUMBER(REGEXP_SUBSTR(BES.GROUP_ATTR_12,'[^-]+',1,1)) = ED.EVENT_DISCOUNT_ID
      AND TO_NUMBER(REGEXP_SUBSTR(BES.GROUP_ATTR_12,'[^-]+',1,2)) = ED.CATALOGUE_CHANGE_ID
      AND ED.EVENT_DISCOUNT_ID = EDS.EVENT_DISCOUNT_ID(+)
      AND ED.CATALOGUE_CHANGE_ID = EDS.CATALOGUE_CHANGE_ID(+)
    AND BES.GROUP_ATTR_12 IS NOT NULL 
  AND UPPER(BES.GROUP_ATTR_12) != 'NULL'
GROUP BY
  BILLING_ACCT_NBR 
  ,NVL(TIO.DESCRIPTION, BES.GROUP_ATTR_6 ||' - '||BES.GROUP_ATTR_7)
  ,ES.EVENT_TYPE_ID
  ,NVL(TIO.Cost_Band_Desc,BES.GROUP_ATTR_6)
  ,NVL(TIO.EVENT_CLASS_NAME,BES.GROUP_ATTR_7) 
  ,BES.GROUP_ATTR_3 
  ,BES.GROUP_ATTR_5 
  ,BES.GROUP_ATTR_7
  ,TO_NUMBER(BES.GROUP_ATTR_4)/1000000 - TO_NUMBER(EDS.DISCOUNT_MNY)/10000
  ,ED.DISCOUNT_NAME
  ,BES.GROUP_ATTR_9 
  ,DECODE(TAM.UF_FORMAT,'VAR','M2M','MVNO')
  ,PLAN.PLAN_NAME ||'-'|| ED.DISCOUNT_NAME 
  ,DECODE(BES.GROUP_ATTR_9,'UNKNOWN','',BES.GROUP_ATTR_9)
  ,BES.GROUP_ATTR_8  
  ,BES.GROUP_ATTR_13
  ,TAM.CUSTOMER_NAME
  ,TAM.CUST_TYPE
  ,BES.EVENT_SUMMARY_ID
  ,BS.BILL_SEQ
  ,TIO.ORDER_NUM 
  ,'1-' || TOP.SEQ || '-0'|| ED.EVENT_DISCOUNT_ID || '-'  ||BES.GROUP_ATTR_8
    WITH READ ONLY;

GRANT SELECT ON TMOBILE_CUSTOM.INVOICESECTIONDETAILSUSAGEVIEW TO UNIF_ADMIN;
  
-- MRC

CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."INVOICESECTIONDETAILSMRCVIEW" ("DIST_INDICATOR","UNIQUE_ID","COST_BAND_DESC", "EVENT_CLASS","DESCRIPTION","PLAN", "TECH_TYPE", "TYPE","QUANTITY", "UNIT_PRICE", "TOTAL_AMOUNT", "PARTNER_NAME", "TLO_OBJECT_ID", "BILLING_TARIFF_NAME", "EVENT_SUMMARY_ID", "ACCOUNT_NUM", "BILL_SEQ","UNIT_TYPE","CATEGORY") AS 
  SELECT
SUBSTR(GROUP_ATTR_8,-1,1) DIST_INDICATOR
,'2-' || TOP.SEQ || '-0000-' || BILLEVENT.GROUP_ATTR_8 UNIQUE_ID
,BILLEVENT.GROUP_ATTR_6 COST_BAND_DESC
,BILLEVENT.GROUP_ATTR_7 EVENT_CLASS
,CASE WHEN GROUP_ATTR_20 = 'PRO' THEN GROUP_ATTR_7 || '-Prorated'
     WHEN GROUP_ATTR_20 = 'REV' THEN GROUP_ATTR_7 || '-Reversal'
       WHEN GROUP_ATTR_20 = 'ACT' THEN 'Subscriber Count' || '-Activation'
    WHEN (TAM.ACCT_TYPE IN ('M2M', 'M2M IOT','POS IOT') AND
         UPPER(BILLEVENT.Group_attr_9) = 'PARTIAL') THEN
          'Days Charged for partial months of ' ||
          CONFIG.PPA_NAME_DESCRIPTION || ' ( ' || BILLEVENT.GROUP_ATTR_11/10000 ||' Contributing MSISDNS )'
    ELSE
          CONFIG.PPA_NAME_DESCRIPTION
END DESCRIPTION
--,PLAN.PLAN_NAME
,(CASE WHEN GROUP_ATTR_3 LIKE '%WHSTIPV4%' THEN 'Public Static IP Functionality IPv4' 
 ELSE PLAN.PLAN_NAME END) PLAN_NAME
,BILLEVENT.GROUP_ATTR_16 Tech
,CONFIG.TYPE
,SUM((CASE WHEN GROUP_ATTR_20 = 'REV' THEN  -1*(TO_NUMBER(BILLEVENT.SUM_ATTR_1))
           ELSE (TO_NUMBER(BILLEVENT.SUM_ATTR_1)) 
    END))/10000 QUANTITY
,ROUND(TO_NUMBER(BILLEVENT.GROUP_ATTR_4)/1000000,5) CHARGING_RATE
,ROUND((SUM(TO_NUMBER(BILLEVENT.SUM_ATTR_2))/10000),2) Total_Amount
,TAM.CUSTOMER_NAME PARTNERNAME
,BILLEVENT.GROUP_ATTR_5 TLO_Object_ID
,BILLEVENT.GROUP_ATTR_3 Billing_Tariff_Name
,EVENTSUM.EVENT_SUMMARY_ID,BILLEVENT.ACCOUNT_NUM,BILLEVENT.BILL_SEQ,'MRC',
PLAN.CATEGORYVALUE
FROM
GENEVA_ADMIN.PVBILLEVENTSUMMARY6 BILLEVENT,
      GENEVA_ADMIN.PVEVENTSUMMARY2 EVENTSUM,
      --TMOBILE_CUSTOM.TOMS_OFFERNAMEMAPPING TOM,
    TMOBILE_CUSTOM.GENPLANNAMEMAPVIEW_MRC  PLAN,
      TMOBILE_CUSTOM.TMO_OFFERPLANID_80 TOP,
      TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM,
       (SELECT distinct TARIFF_ID , TARIFF_NAME FROM TMOBILE_CUSTOM.TMO_OFFERPLANID_80 
       WHERE TARIFF_ID<0
         UNION ALL  
         SELECT   TARIFF_ID ,TARIFF_NAME 
         FROM        TARIFF           
         WHERE  CATALOGUE_CHANGE_ID =
         (SELECT CATALOGUE_CHANGE_ID
         FROM CATALOGUECHANGE
         WHERE CATALOGUE_STATUS = 3)
         ) TF,
    TMOBILE_CUSTOM.TMO_MRC_CONFIG CONFIG
WHERE
TAM.BILLING_ACCT_NBR = BILLEVENT.ACCOUNT_NUM
AND TAM.BILLING_EVENT_SRC = BILLEVENT.GROUP_ATTR_1
      AND TAM.RATING_ACCT_NBR = TOP.RATING_ACCT_NBR
      AND TAM.REFACTORED_FLAG = 'T'
      AND TOP.TOMS_OBJECT_ID = PLAN.TOMSOBJID
      AND PLAN.TOMSOBJID = BILLEVENT.GROUP_ATTR_5
      AND TOP.TARIFF_ID = TF.TARIFF_ID
    AND TF.TARIFF_NAME = PLAN.TARIFF_NAME
    AND PLAN.ATTRIBUTE_NAME = CONFIG.PPA_NAME
    AND PLAN.RBTARIFFID = TOP.TARIFF_ID
      AND ((BILLEVENT.GROUP_ATTR_3 NOT LIKE '%IOT%' AND PLAN.TARIFF_NAME = BILLEVENT.GROUP_ATTR_3) 
      OR (BILLEVENT.GROUP_ATTR_3 LIKE '%IOT%' AND (PLAN.TARIFF_NAME = BILLEVENT.GROUP_ATTR_3 OR PLAN.TARIFF_DESC  = BILLEVENT.GROUP_ATTR_3 OR (PLAN.TARIFF_DESC = SUBSTR(BILLEVENT.GROUP_ATTR_3,0,LENGTH(BILLEVENT.GROUP_ATTR_3)- 4)) 
      OR (PLAN.TARIFF_DESC = SUBSTR(BILLEVENT.GROUP_ATTR_3,0,LENGTH(BILLEVENT.GROUP_ATTR_3)- 3) ))) OR PLAN.TARIFF_NAME = BILLEVENT.GROUP_ATTR_7) 
    AND BILLEVENT.EVENT_SUMMARY_ID = EVENTSUM.EVENT_SUMMARY_ID
    AND EVENTSUM.EVENT_SUMMARY_ID = 85
    AND CONFIG.TYPE = SUBSTR(BILLEVENT.GROUP_ATTR_8,3,3)
    AND ( CONFIG.PPA_NAME = BILLEVENT.GROUP_ATTR_7    or ( BILLEVENT.ACCOUNT_NUM = 'ACC000207' 
      AND ( ( CONFIG.PPA_NAME like 'Plan Name%' and CONFIG.PPA_NAME = TOP.TARIFF_NAME )  
      OR ( CONFIG.PPA_NAME like 'One Time Charge%' )) ) ) 
    AND CONFIG.DISTRIBUTE=SUBSTR(BILLEVENT.GROUP_ATTR_8,-1)   
GROUP BY
TAM.CUSTOMER_NAME --PARTNERNAME
,BILLEVENT.GROUP_ATTR_3 --Billing Tariff Name
,BILLEVENT.GROUP_ATTR_4 --CHARGING_RATE
,BILLEVENT.GROUP_ATTR_5 --TLO Object ID
,BILLEVENT.GROUP_ATTR_6 --COST_BAND_DESC
,BILLEVENT.GROUP_ATTR_7 --EVENT_CLASS
,BILLEVENT.GROUP_ATTR_16 --Tech
,CONFIG.TYPE
,CASE WHEN GROUP_ATTR_20 = 'PRO' THEN GROUP_ATTR_7 || '-Prorated'
      WHEN GROUP_ATTR_20 = 'REV' THEN GROUP_ATTR_7 || '-Reversal'
      WHEN GROUP_ATTR_20 = 'ACT' THEN 'Subscriber Count' || '-Activation'
      WHEN (TAM.ACCT_TYPE IN ('M2M', 'M2M IOT','POS IOT') AND
         UPPER(BILLEVENT.Group_attr_9) = 'PARTIAL') THEN
          'Days Charged for partial months of ' ||
          CONFIG.PPA_NAME_DESCRIPTION || ' ( ' || BILLEVENT.GROUP_ATTR_11/10000 ||' Contributing MSISDNS )'
    ELSE
         CONFIG.PPA_NAME_DESCRIPTION
END
,EVENTSUM.EVENT_SUMMARY_ID
,BILLEVENT.ACCOUNT_NUM
,BILLEVENT.BILL_SEQ
,(CASE WHEN GROUP_ATTR_3 LIKE '%WHSTIPV4%' THEN 'Public Static IP Functionality IPv4' 
 ELSE PLAN.PLAN_NAME END)
,SUBSTR(GROUP_ATTR_8,-1,1) 
,'2-' || TOP.SEQ || '-0000-' || BILLEVENT.GROUP_ATTR_8,PLAN.CATEGORYVALUE 
 WITH READ ONLY;
  
GRANT SELECT ON TMOBILE_CUSTOM.INVOICESECTIONDETAILSMRCVIEW TO UNIF_ADMIN;  
    --- Adjustments
  
CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."INVOICESECTIONDETAILSADJVIEW" ("DIST_INDICATOR","UNIQUE_ID","DESCRIPTION", "TYPE", "QUANTITY", "UNIT_PRICE", "TOTAL_AMOUNT", "PARTNER_NAME", "EVENT_SUMMARY_ID", "ACCOUNT_NUM", "BILL_SEQ","UNIT_TYPE", "ADJ_DATE") AS 
 SELECT 
SUBSTR(GROUP_ATTR_4,-1,1) DIST_INDICATOR
,'3-' || LPAD(BILLEVENT.GROUP_ATTR_7,4,'0') ||'-'||LPAD(BILLEVENT.GROUP_ATTR_9,4,'0')|| '-' || SUBSTR(BILLEVENT.GROUP_ATTR_4,3) UNIQUE_ID
,CASE WHEN ADJ.ADJUSTMENT_TYPE_ID IN (69,23,86,128) THEN 
   BILLEVENT.GROUP_ATTR_8 || ' - ' || PLAN.PLAN_NAME || ' - ' || BILLEVENT.GROUP_ATTR_10 
 ELSE BILLEVENT.GROUP_ATTR_8 || ' - ' || BILLEVENT.GROUP_ATTR_10 END DESCRIPTION
,'ADJ',SUM(TO_NUMBER(BILLEVENT.SUM_ATTR_1)) QUANTITY
,BILLEVENT.GROUP_ATTR_14 CHARGING_RATE
,SUM(TO_NUMBER(BILLEVENT.SUM_ATTR_2))/10000 Total_Amount
,TAM.CUSTOMER_NAME PARTNERNAME
,BILLEVENT.EVENT_SUMMARY_ID
,BILLEVENT.ACCOUNT_NUM,BILLEVENT.BILL_SEQ
,(CASE 
     WHEN BILLEVENT.GROUP_ATTR_4 LIKE '3-%' THEN SUBSTR(BILLEVENT.GROUP_ATTR_4,3,3)
     ELSE BILLEVENT.GROUP_ATTR_4 
 END) UNIT_TYPE
,TO_DATE(TO_CHAR(TO_DATE(BILLEVENT.GROUP_ATTR_6,'YYYYMMDD'),'MM/DD/YYYY'),'MM/DD/YYYY') ADJ_DATE
FROM GENEVA_ADMIN.PVBILLEVENTSUMMARY6 BILLEVENT,
TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM,
GENEVA_ADMIN.PVEVENTSUMMARY2 EVENT,
TMOBILE_CUSTOM.GENPLANNAMEMAPVIEW PLAN,
GENEVA_ADMIN.ADJUSTMENTTYPE ADJ
WHERE 
TAM.BILLING_ACCT_NBR = BILLEVENT.ACCOUNT_NUM
AND TAM.BILLING_EVENT_SRC = BILLEVENT.GROUP_ATTR_1
AND TAM.REFACTORED_FLAG = 'T'
AND BILLEVENT.EVENT_SUMMARY_ID = EVENT.EVENT_SUMMARY_ID
AND EVENT.EVENT_SUMMARY_ID = 86
AND ADJ.ADJUSTMENT_TYPE_NAME = BILLEVENT.GROUP_ATTR_8
AND BILLEVENT.GROUP_ATTR_3 = PLAN.TARIFF_NAME(+)
AND BILLEVENT.GROUP_ATTR_5 = PLAN.TOMSOBJID(+)
GROUP BY
TAM.CUSTOMER_NAME --PARTNERNAME
,BILLEVENT.GROUP_ATTR_6 --Adjustment Date
,BILLEVENT.GROUP_ATTR_7 --Adjustment Sequence
--,BILLEVENT.GROUP_ATTR_8 --Adjustment Name
,BILLEVENT.GROUP_ATTR_9 --Adjustment Type
--,BILLEVENT.GROUP_ATTR_10 --Adjustment Description
,BILLEVENT.GROUP_ATTR_14 --CHARGING_RATE
,BILLEVENT.EVENT_SUMMARY_ID
,(CASE 
     WHEN BILLEVENT.GROUP_ATTR_4 LIKE '3-%' THEN SUBSTR(BILLEVENT.GROUP_ATTR_4,3,3)
     ELSE BILLEVENT.GROUP_ATTR_4 
 END)
 ,BILLEVENT.ACCOUNT_NUM
 ,BILLEVENT.BILL_SEQ
 ,SUBSTR(GROUP_ATTR_4,-1,1) 
,'3-' || LPAD(BILLEVENT.GROUP_ATTR_7,4,'0') ||'-'||LPAD(BILLEVENT.GROUP_ATTR_9,4,'0')|| '-' || SUBSTR(BILLEVENT.GROUP_ATTR_4,3)
,CASE WHEN ADJ.ADJUSTMENT_TYPE_ID IN (69,23,86,128) THEN 
   BILLEVENT.GROUP_ATTR_8 || ' - ' || PLAN.PLAN_NAME || ' - ' || BILLEVENT.GROUP_ATTR_10 
 ELSE BILLEVENT.GROUP_ATTR_8 || ' - ' || BILLEVENT.GROUP_ATTR_10 END
 UNION
SELECT 
SUBSTR(BILL_DATA.UNIQUE_ID,-1,1) DIST_INDICATOR
,BILL_DATA.UNIQUE_ID
,BILL_DATA.TA_1  DESCRIPTION
,'ADJ' TYPE,TO_NUMBER('') QUANTITY,'' UNIT_PRICE
,TO_NUMBER(BILL_DATA.TA_3)/100 TOTAL_AMOUNT
,TAM.CUSTOMER_NAME PARTNER_NAME,86 EVENT_SUMMARY_ID
,BILL_DATA.ACCOUNT_NUM , BILL_DATA.BILL_SEQ
,REGEXP_SUBSTR(BILL_DATA.UNIQUE_ID,'[^-]+', 1,4) UNIT_TYPE
,TO_DATE(BILL_DATA.TA_2,'MM/DD/YYYY') ADJ_DATE
FROM
TMOBILE_CUSTOM.TMO_BILLDATATAG_DETAILS BILL_DATA,
TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
WHERE 
TAM.BILLING_ACCT_NBR = BILL_DATA.ACCOUNT_NUM
AND TAM.REFACTORED_FLAG = 'T'
AND BILL_DATA.BILL_VERSION = (SELECT MAX(B.BILL_VERSION) FROM GENEVA_ADMIN.BILLSUMMARY B WHERE B.ACCOUNT_NUM=BILL_DATA.ACCOUNT_NUM AND B.BILL_SEQ=BILL_DATA.BILL_SEQ  AND B.BILL_STATUS IN (1,7,8))
AND REGEXP_SUBSTR(BILL_DATA.UNIQUE_ID,'[^-]+', 1,1) = 3
WITH READ ONLY; 
GRANT SELECT ON TMOBILE_CUSTOM.INVOICESECTIONDETAILSADJVIEW TO UNIF_ADMIN;
  -- TAX
  
CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."INVOICESECTIONDETAILSTAXVIEW" ("UNIQUE_ID","DESCRIPTION","TYPE","TOTAL_AMOUNT","ACCOUNT_NUM","BILL_SEQ") AS
WITH tax AS
  (SELECT ust.* ,
    (SUBSTR(UST_JCODE, 1, 2)) state_code,
    (SUBSTR(UST_JCODE, 3, 3)) COUNTY_CODE,
    (SUBSTR(UST_JCODE, 6)) City_CODE
  FROM PVUSTTAXSUMMARY ust,
  BILLSUMMARY b
  where b.account_num = ust.account_num
  and b.bill_seq = ust.bill_seq
  and b.bill_status in (1,7,8)
  and b.bill_version = ust.BILL_VERSION
  AND ust.TAX_AMOUNT_MNY != 0
  ),
  taxsumm AS
  (SELECT tax.*,
    (SELECT MIN( agg.state_code
      || agg.county_code
      || agg.city_code) jcode
    FROM TMOBILE_CUSTOM.TAX_AGGREGATION_80 agg
    WHERE tax.EXTERNAL_TAX_TYPE_ID = agg.TAX_TYPE_ID
    AND tax.AUTHORITY              = agg.TAX_AUTH_ID
    AND tax.state_code             =DECODE(agg.state_code,'XX',tax.state_code,agg.state_code)
    AND tax.county_code            =DECODE(agg.county_code,'XXX',tax.county_code,agg.county_code)
    AND tax.city_code              =DECODE(agg.city_code,'XXXX',tax.city_code,agg.city_code)
    GROUP BY tax_type_id,
      tax_auth_id
    ) masked_jcode
  FROM tax
  ),
  taxsumm_final as
  (
SELECT
  '4-000' || CASE WHEN taxagg.CONSOLIDATION_IND IS NOT NULL THEN '1'
    ELSE decode (NVL(taxagg.TAX_AUTH_ID, taxsumm.AUTHORITY), 1, '0', 2, '1', 3, '2', 4, '3', 5, '4', 6, '6', 7, '7', 8, '9', '999' ) END || '-'
   || CASE WHEN taxagg.CONSOLIDATION_IND IS NOT NULL
    THEN LPAD(SUBSTR(taxsumm.UST_JCODE, 1, 2),4,'0')
  ELSE LPAD(NVL(taxagg.TAX_TYPE_ID, taxsumm.EXTERNAL_TAX_TYPE_ID),4,'0') END
   || '-' ||CASE WHEN taxagg.SURCHARGE_IND IS NULL THEN 'GTF' ELSE 'OTF' END UNIQUE_ID,
  CASE
    WHEN taxagg.CONSOLIDATION_IND IS NOT NULL
    THEN '1'
    ELSE decode (NVL(taxagg.TAX_AUTH_ID, taxsumm.AUTHORITY), 1, '0', 2, '1', 3, '2', 4, '3', 5, '4', 6, '6', 7, '7', 8, '9', '999' )
  END Tax_Auth,
  CASE
    WHEN taxagg.CONSOLIDATION_IND IS NOT NULL
    THEN SUBSTR(taxsumm.UST_JCODE, 1, 2)
  ELSE NVL(taxagg.TAX_TYPE_ID, taxsumm.EXTERNAL_TAX_TYPE_ID) END Tax_Type,
  CASE
    WHEN to_number(SUBSTR(taxsumm.UST_JCODE, 1, 2)) = '00'
    THEN ''
    ELSE lstate.LOCNAMESTATE
  END STATE_NAME,
  NVL(taxagg.BILL_TEXT, exttaxtype.EXTERNAL_TAX_TYPE_NAME) Tax_Desc,
  CASE
    WHEN taxagg.SURCHARGE_IND IS NULL
    THEN 'GTF'
    ELSE 'OTF'
  END GROUP_TYPE,
  ROUND(SUM(taxsumm.TAX_AMOUNT_MNY)/10000,2) Tax_Amount,
  taxsumm.ACCOUNT_NUM,
  taxsumm.BILL_SEQ
FROM taxsumm,
  geneva_admin.PVUSTEXTERNALTAXTYPE2 exttaxtype,
  geneva_admin.LOCSTATE lstate,
  TMOBILE_CUSTOM.TAX_AGGREGATION_80 taxagg
WHERE taxsumm.EXTERNAL_TAX_TYPE_ID = exttaxtype.EXTERNAL_TAX_TYPE_ID
AND taxsumm.UST_CHARGE_GROUP_ID    = exttaxtype.UST_CHARGE_GROUP_ID
AND ((lstate.LOCGEOSTATE           = to_number(SUBSTR(taxsumm.UST_JCODE, 1, 2)))
OR (taxsumm.UST_JCODE              = '000000000'
AND lstate.LOCGEOSTATE             = 1))
AND taxsumm.EXTERNAL_TAX_TYPE_ID   = taxagg.TAX_TYPE_ID(+)
AND taxsumm.AUTHORITY              = taxagg.TAX_AUTH_ID(+)
AND taxsumm.masked_jcode           = NVL(taxagg.state_code(+),'XX')
  ||NVL(taxagg.county_code(+),'XXX')
  ||NVL(taxagg.city_code(+),'XXXX')
GROUP BY
  '4-000' || CASE WHEN taxagg.CONSOLIDATION_IND IS NOT NULL THEN '1'
    ELSE decode (NVL(taxagg.TAX_AUTH_ID, taxsumm.AUTHORITY), 1, '0', 2, '1', 3, '2', 4, '3', 5, '4', 6, '6', 7, '7', 8, '9', '999' ) END || '-'
   || CASE WHEN taxagg.CONSOLIDATION_IND IS NOT NULL
    THEN LPAD(SUBSTR(taxsumm.UST_JCODE, 1, 2),4,'0')
  ELSE LPAD(NVL(taxagg.TAX_TYPE_ID, taxsumm.EXTERNAL_TAX_TYPE_ID),4,'0') END
   || '-' ||CASE WHEN taxagg.SURCHARGE_IND IS NULL THEN 'GTF' ELSE 'OTF' END,
  CASE
    WHEN taxagg.CONSOLIDATION_IND IS NOT NULL
    THEN '1'
    ELSE decode (NVL(taxagg.TAX_AUTH_ID, taxsumm.AUTHORITY), 1, '0', 2, '1', 3, '2', 4, '3', 5, '4', 6, '6', 7, '7', 8, '9', '999' )
  END,
 -- NVL(taxagg.TAX_TYPE_ID, taxsumm.EXTERNAL_TAX_TYPE_ID),
  CASE
    WHEN taxagg.CONSOLIDATION_IND IS NOT NULL
    THEN SUBSTR(taxsumm.UST_JCODE, 1, 2)
  ELSE NVL(taxagg.TAX_TYPE_ID, taxsumm.EXTERNAL_TAX_TYPE_ID) END,
  CASE
    WHEN to_number(SUBSTR(taxsumm.UST_JCODE, 1, 2)) = '00'
    THEN ''
    ELSE lstate.LOCNAMESTATE
  END,
  NVL(taxagg.BILL_TEXT, exttaxtype.EXTERNAL_TAX_TYPE_NAME),
   CASE
    WHEN taxagg.SURCHARGE_IND IS NULL
    THEN 'GTF'
    ELSE 'OTF'
  END,
  taxsumm.ACCOUNT_NUM,
  taxsumm.BILL_SEQ
   )
   SELECT UNIQUE_ID,NVL2(STATE_NAME,INITCAP(TRIM(STATE_NAME)) ||' '|| TAX_DESC,TAX_DESC) DESCRIPTION,GROUP_TYPE,TAX_AMOUNT,ACCOUNT_NUM,BILL_SEQ 
   from taxsumm_final where TAX_AMOUNT !=0
 WITH READ ONLY;
      
GRANT SELECT ON TMOBILE_CUSTOM.INVOICESECTIONDETAILSTAXVIEW TO UNIF_ADMIN; 