BEGIN
  execute immediate 'CREATE INDEX TMOBILE_CUSTOM.USAGE_LINE_ITEM_INDEX ON TMOBILE_CUSTOM.TMO_INVOICE_USAGE_LINE_ITEM(ACCOUNT_NUM, EVENT_SEQ, EVENT_TYPE_ID, TOMS_TLO_ID)';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
BEGIN
  execute immediate 'CREATE INDEX TMOBILE_CUSTOM.ACTIVESUSPENDDAYS_INDEX ON TMOBILE_CUSTOM.TMO_INVOICE_ACTIVESUSPENDDAYS(CUSTOMER_REF,MSISDN,TARIFF_ID, TOMS_OBJECT_ID)';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
