-- For USG lineItemDetails:
CREATE OR REPLACE  VIEW TMOBILE_CUSTOM.SUBBILLEDUSAGE_VIEW ("ACCOUNT_NUM", "BILL_SEQ", "PARTNER_NAME", "EVENT_SEQ", "EVENT_TYPE_ID", "EVENT_SUMMARY_ID",  "COST_BAND", "EVENT_CLASS", "BILLING_TARIFF_NAME", "TLO_OBJECT_ID", "CHARGING_RATE", "DISCOUNT_NAME", "TECH_TYPE", "CDR_TYPE", "DESCRIPTION", "PLAN", "EVENT_SOURCE", "MSISDN", "EVENT_COUNT", "USAGE_TOTAL", "CHARGE_TOTAL") AS 
SELECT
  BILLING_ACCT_NBR ACCOUNT_NUM
  ,BS.BILL_SEQ
  ,TAM.CUSTOMER_NAME PARTNER_NAME
  ,TCUH.EVENT_SEQ EVENT_SEQ
  ,EVENT_TYPE_ID
  ,EVENT_SUMMARY_ID
  ,TRIM(CASE WHEN TCET.EVENT_TYPE =2 THEN NVL(COST_BAND,NVL(COST_BAND_DESC,'SMS'))
   ELSE  NVL(COST_BAND,NVL(COST_BAND_DESC,'NULL')) END) COST_BAND
  ,NVL(TRIM(EVENT_CLASS),'NULL') EVENT_CLASS
  ,BILLING_TARIFF_NAME
  ,TOMS_TLO_ID TLO_OBJECT_ID
  ,(CASE WHEN UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%GPRS%'
         OR   UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%SUM_VOICE%'
         OR   UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%SUM_INTL_VOICE%'
         THEN
       CASE WHEN FACTOR IS NOT NULL THEN (TO_NUMBER(CHARGING_RATE)/FACTOR)/1000000
       ELSE TO_NUMBER(CHARGING_RATE)/1000000 END
         ELSE CASE WHEN FACTOR IS NOT NULL THEN (TO_NUMBER(CHARGING_RATE)/FACTOR)/10000
          ELSE TO_NUMBER(CHARGING_RATE)/10000 END
    END) CHARGING_RATE
  ,DISCOUNT_NAME
  ,DECODE(TECH_TYPE,'UNKNOWN','',TECH_TYPE)
  ,DECODE(TAM.UF_FORMAT,'Var','M2M','MVNO') CDR_TYPE
  -- Display Fields
  ,NVL(COST_BAND,COST_BAND_DESC)||' - '||(EVENT_CLASS) DESCRIPTION
  ,DECODE(TOM.OBJECT_NAME,BILLING_TARIFF_NAME,BILLING_TARIFF_NAME,TOM.OBJECT_NAME ||'-'||BILLING_TARIFF_NAME) PLAN
  ,EVENT_SOURCE
  ,EVENT_SOURCE MSISDN
  ,SUM(EVENT_COUNT) EVENT_COUNT
  ,SUM(CASE WHEN UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%GPRS%' THEN TO_NUMBER(NVL(ROUNDED_DURATION,EVENT_COUNT))/1048576
          WHEN  UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%SUM_VOICE%' OR UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%SUM_INTL_VOICE%' THEN TO_NUMBER(NVL(ROUNDED_DURATION,EVENT_COUNT))/60
    ELSE TO_NUMBER(NVL(ROUNDED_DURATION,EVENT_COUNT)) END) USAGE_TOTAL
  ,SUM(CASE WHEN FACTOR IS NOT NULL THEN ((TO_NUMBER(COST_TOTAL))/FACTOR)/10000
   ELSE (TO_NUMBER(COST_TOTAL))/10000 END) CHARGE_TOTAL
FROM
  TMOBILE_CUSTOM.TMO_INVOICE_USAGE_LINE_ITEM TCUH
  ,TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM
  ,TMOBILE_CUSTOM.TOMS_OFFERNAMEMAPPING TOM
  ,TMOBILE_CUSTOM.TMO_EVENT_MAPPING TCET
  ,BILLSUMMARY BS
WHERE
  TAM.RATING_ACCT_NBR=TCUH.ACCOUNT_NUM
  AND TOM.OBJECT_ID = TCUH.TOMS_TLO_ID
  AND TAM.REFACTORED_FLAG = 'T'
  AND TCUH.EVENT_TYPE_ID = TCET.EVENT_TYPE
  AND BS.ACCOUNT_NUM = TAM.BILLING_ACCT_NBR
  AND BS.EVENT_SEQ  = TCUH.EVENT_SEQ
  AND BS.BILL_VERSION = (SELECT MAX(BILL_VERSION) FROM BILLSUMMARY B WHERE B.ACCOUNT_NUM=BS.ACCOUNT_NUM AND B.BILL_SEQ=BS.BILL_SEQ  AND BS.BILL_STATUS IN (1,7,8))
GROUP BY
  BILLING_ACCT_NBR
  ,BS.BILL_SEQ
  ,TAM.CUSTOMER_NAME
  ,TCUH.EVENT_SEQ
  ,EVENT_TYPE_ID
  ,EVENT_SUMMARY_ID
  ,TRIM(CASE WHEN TCET.EVENT_TYPE =2 THEN NVL(COST_BAND,NVL(COST_BAND_DESC,'SMS'))
   ELSE  NVL(COST_BAND,NVL(COST_BAND_DESC,'NULL')) END)
  ,NVL(TRIM(EVENT_CLASS),'NULL')
  ,BILLING_TARIFF_NAME
  ,TOMS_TLO_ID
  ,(CASE WHEN UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%GPRS%'
         OR   UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%SUM_VOICE%'
         OR   UPPER(TCET.EVENT_SUMMARY_NAME) LIKE '%SUM_INTL_VOICE%'
         THEN
       CASE WHEN FACTOR IS NOT NULL THEN (TO_NUMBER(CHARGING_RATE)/FACTOR)/1000000
       ELSE TO_NUMBER(CHARGING_RATE)/1000000 END
         ELSE CASE WHEN FACTOR IS NOT NULL THEN (TO_NUMBER(CHARGING_RATE)/FACTOR)/10000
          ELSE TO_NUMBER(CHARGING_RATE)/10000 END
    END)
  ,DISCOUNT_NAME
  ,DECODE(TECH_TYPE,'UNKNOWN','',TECH_TYPE)
  ,DECODE(TAM.UF_FORMAT,'Var','M2M','MVNO')
  ,NVL(COST_BAND,COST_BAND_DESC)||' - '||EVENT_CLASS
  ,DECODE(TOM.OBJECT_NAME,BILLING_TARIFF_NAME,BILLING_TARIFF_NAME,TOM.OBJECT_NAME ||'-'||BILLING_TARIFF_NAME)
  ,EVENT_SOURCE
WITH READ ONLY;
GRANT SELECT ON TMOBILE_CUSTOM.SUBBILLEDUSAGE_VIEW TO UNIF_ADMIN;

-- For STD-Recurring MRC type lineItemDetails:
CREATE OR REPLACE VIEW TMOBILE_CUSTOM.SUBACTIVEDAYS_VIEW AS
WITH  ACCOUNTS AS(
SELECT TAM.CUSTOMER_NAME PARTNER_NAME, TAM.RATING_CUST_REF, TAM.BILLING_ACCT_NBR ACCOUNT_NUM,
 BS.EVENT_SEQ, 
(BILL_DTM-START_OF_BILL_DTM) AS DAYS,BS.BILL_SEQ, TAM.UF_FORMAT
FROM 
 TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM,
 GENEVA_ADMIN.BILLSUMMARY BS
 WHERE TAM.REFACTORED_FLAG = 'T'
 AND BS.ACCOUNT_NUM = TAM.BILLING_ACCT_NBR
 AND BS.BILL_STATUS IN (1,7,8) 
),
EVENTSUMMDATA AS (
SELECT ACC.*,T.TARIFF_NAME BILLING_TARIFF_NAME, --BILLING TARIFF NAME
    BES.GROUP_ATTR_5 TLO_OBJECT_ID, --TLO OBJECT ID
    BES.GROUP_ATTR_9 FLAG,
	T.TARIFF_ID
FROM ACCOUNTS ACC,
GENEVA_ADMIN.BILLEVENTSUMMARY BES,
GENEVA_ADMIN.TARIFF T
WHERE BES.ACCOUNT_NUM = ACC.ACCOUNT_NUM
 AND BES.BILL_SEQ = ACC.BILL_SEQ
 AND BES.EVENT_SUMMARY_ID = 85
 AND T.TARIFF_NAME= BES.GROUP_ATTR_3
 AND T.CATALOGUE_CHANGE_ID = (SELECT CATALOGUE_CHANGE_ID FROM CATALOGUECHANGE WHERE CATALOGUE_STATUS = 3)
 )
 SELECT ESD.ACCOUNT_NUM,ESD.BILL_SEQ, ESD.PARTNER_NAME, ESD.FLAG, ESD.BILLING_TARIFF_NAME,
  ESD.TLO_OBJECT_ID ,ACTDAYS.MSISDN, ACTDAYS.ACTIVEDAYS
 FROM
 EVENTSUMMDATA ESD,
 TMOBILE_CUSTOM.TMO_INVOICE_ACTIVESUSPENDDAYS ACTDAYS
 WHERE ACTDAYS.CUSTOMER_REF = ESD.RATING_CUST_REF
 AND ACTDAYS.EVENT_SEQ = ESD.EVENT_SEQ
 AND ACTDAYS.TARIFF_ID = ESD.TARIFF_ID
 AND ACTDAYS.TOMS_OBJECT_ID = ESD.TLO_OBJECT_ID
 AND (((ESD.UF_FORMAT = 'Var' and ACTDAYS.ACTIVEDAYS != 0) AND
       ((ESD.DAYS != ACTDAYS.ACTIVEDAYS AND ESD.FLAG = 'PARTIAL') OR
       (ESD.DAYS = ACTDAYS.ACTIVEDAYS AND ESD.FLAG = 'WHOLE'))) OR
       (ESD.UF_FORMAT = 'Wholesale' and ACTDAYS.ACTIVEDAYS != 0))
WITH READ ONLY;
GRANT SELECT ON TMOBILE_CUSTOM.SUBACTIVEDAYS_VIEW TO UNIF_ADMIN;

-- For HSD Charge MRC type lineItemDetails:
CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."SUBHSDCHARGE_VIEW"("PARTNER_NAME","MSISDN", "PLAN_NAME", "PRODUCT_NAME", "BUCKET_LIMIT", "BILLING_TARIFF_NAME", "ACCOUNT_NUM", "BILL_SEQ", "CHARGING_RATE", "TLO_OBJECT_ID", "COST_BAND", "QUANTITY", "EVENT_SUMMARY_ID", "TECH_TYPE" ) AS 
SELECT TMO_TEST.GROUP_ATTR_1,SUB_HSD_CHARGE.MSISDN, SUB_HSD_CHARGE.PLAN_NAME, SUB_HSD_CHARGE.PRODUCT_NAME, 
SUB_HSD_CHARGE.BUCKET_LIMIT, TMO_TEST.GROUP_ATTR_3 as BILING_TARIFF_NAME, TMO_TEST.ACCOUNT_NUM as ACCOUNT_NUM, TMO_TEST.BILL_SEQ as BILL_SEQ, 
TMO_TEST.CHARGING_RATE,TMO_TEST.GROUP_ATTR_5,TMO_TEST.GROUP_ATTR_6, 
TMO_TEST.SUM_ATTR_3, TMO_TEST.EVENT_SUMMARY_ID,DECODE(TMO_TEST.GROUP_ATTR_16,'UNKNOWN','',TMO_TEST.GROUP_ATTR_16)
FROM TMOBILE_CUSTOM.TMO_INVOICE_SUB_HSD SUB_HSD_CHARGE,  
(SELECT 
      EVENTSUM.EVENT_SUMMARY_NAME,
	  BILLEVENTSUM.ACCOUNT_NUM,
	  BILLEVENTSUM.BILL_SEQ,
	  BILLEVENTSUM.GROUP_ATTR_1, --PARTNER_NAME
	  BILLEVENTSUM.GROUP_ATTR_6, --COST_BAND
      BILLEVENTSUM.GROUP_ATTR_3, --BILLING TARIFF NAME
	  ROUND(TO_NUMBER(BILLEVENTSUM.GROUP_ATTR_4)/1000000,5) CHARGING_RATE, 
      BILLEVENTSUM.GROUP_ATTR_5, --TLO OBJECT ID
	  BILLEVENTSUM.GROUP_ATTR_16,
	  BILLEVENTSUM.SUM_ATTR_1, -- Quantity
	  BILLEVENTSUM.SUM_ATTR_3,	
	  BILLEVENTSUM.EVENT_SUMMARY_ID,
      TOP.SEQ TLO_OBJECT_SEQUENCE,
      TOM.OBJECT_NAME TOMS_OFFER_NAME,
      TF.TARIFF_ID,
	  TAM.RATING_CUST_REF 
  FROM 
      PVBILLEVENTSUMMARY6 BILLEVENTSUM, 
      PVEVENTSUMMARY2 EVENTSUM,
      TMOBILE_CUSTOM.TOMS_OFFERNAMEMAPPING TOM,
      TMOBILE_CUSTOM.TMO_OFFERPLANID_80 TOP,
      TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM,
      TARIFF TF
  WHERE TAM.BILLING_ACCT_NBR = BILLEVENTSUM.ACCOUNT_NUM
      AND TAM.RATING_ACCT_NBR = TOP.RATING_ACCT_NBR
      AND TAM.REFACTORED_FLAG = 'T'
      AND TOP.TOMS_OBJECT_ID = TOM.OBJECT_ID
      AND TOP.TOMS_OBJECT_ID = BILLEVENTSUM.GROUP_ATTR_5
      AND TOP.TARIFF_ID = TF.TARIFF_ID
      AND TF.TARIFF_NAME = BILLEVENTSUM.GROUP_ATTR_3
      AND TF.CATALOGUE_CHANGE_ID = (SELECT CATALOGUE_CHANGE_ID FROM CATALOGUECHANGE C WHERE C.RATING_CATALOGUE_ID IN (  SELECT RATING_CATALOGUE_ID FROM RATINGCATALOGUE WHERE CATALOGUE_STATUS=3  AND CURRENCY_CODE = 'USD'
      AND INVOICING_CO_ID = 2) AND C.CATALOGUE_STATUS=3)
      AND BILLEVENTSUM.EVENT_SUMMARY_ID = EVENTSUM.EVENT_SUMMARY_ID
      AND BILLEVENTSUM.EVENT_SUMMARY_ID IN 85) TMO_TEST	
	  WHERE TMO_TEST.RATING_CUST_REF = SUB_HSD_CHARGE.CUSTOMER_REF 
  GROUP BY 
	  TMO_TEST.GROUP_ATTR_1, 
	  SUB_HSD_CHARGE.MSISDN, 
	  SUB_HSD_CHARGE.PLAN_NAME, 
	  SUB_HSD_CHARGE.PRODUCT_NAME, 
	  SUB_HSD_CHARGE.BUCKET_LIMIT, 
	  TMO_TEST.GROUP_ATTR_3, 
	  TMO_TEST.ACCOUNT_NUM, 
	  TMO_TEST.BILL_SEQ, 
	  TMO_TEST.CHARGING_RATE, 
	  TMO_TEST.GROUP_ATTR_5, 
	  TMO_TEST.GROUP_ATTR_6, 
	  TMO_TEST.SUM_ATTR_3, 
	  TMO_TEST.EVENT_SUMMARY_ID, 
	  DECODE(TMO_TEST.GROUP_ATTR_16,'UNKNOWN','',TMO_TEST.GROUP_ATTR_16)
WITH READ ONLY;
GRANT SELECT ON TMOBILE_CUSTOM.SUBHSDCHARGE_VIEW TO UNIF_ADMIN;