--For NonLTE Penalty MRC type lineItemDetails:
CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."IMEIPENALTY_VIEW"("PARTNER_NAME", "MSISDN", "IMEI", "DEVICE_BOO", "ON_INCORRECT_PLAN_BOO", "BILL_DATE", "ACCOUNT_NUM", "BILL_SEQ", "CHARGING_RATE", "TLO_OBJECT_ID", "COST_BAND", "QUANTITY", "EVENT_SUMMARY_ID", "BILLING_TARIFF_NAME", "TECH_TYPE" ) AS 
SELECT TMO_TEST.GROUP_ATTR_1, M2MUSAGE.MSISDN, M2MUSAGE.IMEI, M2MUSAGE.DEVICE_BOO, M2MUSAGE.ON_INCORRECT_PLAN_BOO, 
M2MUSAGE.BILL_DATE, TMO_TEST.ACCOUNT_NUM as ACCOUNT_NUM, TMO_TEST.BILL_SEQ as BILL_SEQ,
TMO_TEST.CHARGING_RATE,TMO_TEST.GROUP_ATTR_5,TMO_TEST.GROUP_ATTR_6, 
TMO_TEST.SUM_ATTR_3, TMO_TEST.EVENT_SUMMARY_ID, TMO_TEST.GROUP_ATTR_3 as BILLING_TARIFF_NAME,TMO_TEST.GROUP_ATTR_16
FROM TMOBILE_CUSTOM.TMO_M2MUSAGESUMMBYIMEI_80 M2MUSAGE, (
SELECT 
      EVENTSUM.EVENT_SUMMARY_NAME,
	  BILLEVENTSUM.ACCOUNT_NUM,
	  BILLEVENTSUM.BILL_SEQ,
      BILLEVENTSUM.GROUP_ATTR_1, --PARTNER_NAME
	  BILLEVENTSUM.GROUP_ATTR_6, --COST_BAND
      BILLEVENTSUM.GROUP_ATTR_3, --BILLING TARIFF NAME
	  ROUND(TO_NUMBER(BILLEVENTSUM.GROUP_ATTR_4)/1000000,5) CHARGING_RATE,
      BILLEVENTSUM.GROUP_ATTR_5, --TLO OBJECT ID
	  BILLEVENTSUM.GROUP_ATTR_16,
	  BILLEVENTSUM.SUM_ATTR_1, -- Quantity
	  BILLEVENTSUM.SUM_ATTR_3,	
	  BILLEVENTSUM.EVENT_SUMMARY_ID,
      TOP.SEQ TLO_OBJECT_SEQUENCE,
      TOM.OBJECT_NAME TOMS_OFFER_NAME,
      TF.TARIFF_ID,
	  TAM.RATING_ACCT_NBR
  FROM 
      PVBILLEVENTSUMMARY6 BILLEVENTSUM, 
      PVEVENTSUMMARY2 EVENTSUM,
      TMOBILE_CUSTOM.TOMS_OFFERNAMEMAPPING TOM,
      TMOBILE_CUSTOM.TMO_OFFERPLANID_80 TOP,
      TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM,
      TARIFF TF
  WHERE TAM.BILLING_ACCT_NBR = BILLEVENTSUM.ACCOUNT_NUM
      AND TAM.RATING_ACCT_NBR = TOP.RATING_ACCT_NBR
      AND TAM.REFACTORED_FLAG = 'T'
      AND TOP.TOMS_OBJECT_ID = TOM.OBJECT_ID
      AND TOP.TOMS_OBJECT_ID = BILLEVENTSUM.GROUP_ATTR_5
      AND TOP.TARIFF_ID = TF.TARIFF_ID
      AND TF.TARIFF_NAME = BILLEVENTSUM.GROUP_ATTR_3
      AND TF.CATALOGUE_CHANGE_ID = (SELECT CATALOGUE_CHANGE_ID FROM CATALOGUECHANGE C WHERE C.RATING_CATALOGUE_ID IN (  SELECT RATING_CATALOGUE_ID FROM RATINGCATALOGUE WHERE CATALOGUE_STATUS=3  AND CURRENCY_CODE = 'USD'
                   AND INVOICING_CO_ID = 2) AND C.CATALOGUE_STATUS=3)
      AND BILLEVENTSUM.EVENT_SUMMARY_ID = EVENTSUM.EVENT_SUMMARY_ID
      AND BILLEVENTSUM.EVENT_SUMMARY_ID IN
      (85)) TMO_TEST 
	  WHERE  TMO_TEST.RATING_ACCT_NBR = M2MUSAGE.ACCOUNT_NUM 
  GROUP BY 
	  TMO_TEST.GROUP_ATTR_1, 
	  M2MUSAGE.MSISDN, 
	  M2MUSAGE.IMEI, 
	  M2MUSAGE.DEVICE_BOO, 
	  M2MUSAGE.ON_INCORRECT_PLAN_BOO, 
	  M2MUSAGE.BILL_DATE, 
	  TMO_TEST.ACCOUNT_NUM, 
	  TMO_TEST.BILL_SEQ, 
	  TMO_TEST.CHARGING_RATE, 
	  TMO_TEST.GROUP_ATTR_5, 
	  TMO_TEST.GROUP_ATTR_6, 
	  TMO_TEST.SUM_ATTR_3, 
	  TMO_TEST.EVENT_SUMMARY_ID, 
	  TMO_TEST.GROUP_ATTR_3, 
	  TMO_TEST.GROUP_ATTR_16 
WITH READ ONLY;
GRANT SELECT ON TMOBILE_CUSTOM.IMEIPENALTY_VIEW TO UNIF_ADMIN;

--For NUMIMSI1-MRC MRC type lineItemDetails:
CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."NUMIMSI_MRC_VIEW" AS 
SELECT IMSI, PLAN_NAME, PENALITY_FLAG, MRC_FLAG, BILL_DATE
FROM TMOBILE_CUSTOM.TMO_IMSI_LIST 
WITH READ ONLY;
GRANT SELECT ON TMOBILE_CUSTOM.NUMIMSI_MRC_VIEW TO UNIF_ADMIN;
/
BEGIN
  execute immediate 'DROP VIEW TMOBILE_CUSTOM.NUMIMSI10_MRC_VIEW';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
BEGIN
  execute immediate 'DROP VIEW TMOBILE_CUSTOM.NUMIMSI1_MRC_VIEW';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/