-- For HSD Credit MRC type lineItemDetails:
CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."SUBHSDCREDIT_VIEW"("PARTNER_NAME","MSISDN", "PLAN_NAME", "PRODUCT_NAME", "BUCKET_LIMIT", "BILLING_TARIFF_NAME", "ACCOUNT_NUM", "BILL_SEQ", "CHARGING_RATE", "TLO_OBJECT_ID", "COST_BAND", "QUANTITY", "EVENT_SUMMARY_ID", "TECH_TYPE" ) AS 
SELECT TMO_TEST.GROUP_ATTR_1,SUB_HSD_CREDIT.MSISDN, SUB_HSD_CREDIT.PLAN_NAME, SUB_HSD_CREDIT.PRODUCT_NAME, 
SUB_HSD_CREDIT.BUCKET_LIMIT, TMO_TEST.GROUP_ATTR_3 as BILLING_TARIFF_NAME, TMO_TEST.ACCOUNT_NUM as ACCOUNT_NUM, TMO_TEST.BILL_SEQ as BILL_SEQ,
TMO_TEST.CHARGING_RATE,TMO_TEST.GROUP_ATTR_5,TMO_TEST.GROUP_ATTR_6, 
TMO_TEST.SUM_ATTR_3, TMO_TEST.EVENT_SUMMARY_ID,DECODE(TMO_TEST.GROUP_ATTR_16,'UNKNOWN','',TMO_TEST.GROUP_ATTR_16)
FROM TMOBILE_CUSTOM.TMO_INVOICE_SUB_HSD SUB_HSD_CREDIT,  
(SELECT 
      EVENTSUM.EVENT_SUMMARY_NAME,
	  BILLEVENTSUM.ACCOUNT_NUM,
	  BILLEVENTSUM.BILL_SEQ,
      BILLEVENTSUM.GROUP_ATTR_1, --PARTNER_NAME
	  BILLEVENTSUM.GROUP_ATTR_6, --COST_BAND
      BILLEVENTSUM.GROUP_ATTR_3, --BILLING TARIFF NAME
	  ROUND(TO_NUMBER(BILLEVENTSUM.GROUP_ATTR_4)/1000000,5) CHARGING_RATE, 
      BILLEVENTSUM.GROUP_ATTR_5, --TLO OBJECT ID
	  BILLEVENTSUM.GROUP_ATTR_16,
	  BILLEVENTSUM.SUM_ATTR_1, -- Quantity
	  BILLEVENTSUM.SUM_ATTR_3,	
	  BILLEVENTSUM.EVENT_SUMMARY_ID,
      TOP.SEQ TLO_OBJECT_SEQUENCE,
      TOM.OBJECT_NAME TOMS_OFFER_NAME,
      TF.TARIFF_ID,
	  TAM.RATING_CUST_REF
  FROM 
      PVBILLEVENTSUMMARY6 BILLEVENTSUM, 
      PVEVENTSUMMARY2 EVENTSUM,
      TMOBILE_CUSTOM.TOMS_OFFERNAMEMAPPING TOM,
      TMOBILE_CUSTOM.TMO_OFFERPLANID_80 TOP,
      TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM,
      TARIFF TF
  WHERE TAM.BILLING_ACCT_NBR = BILLEVENTSUM.ACCOUNT_NUM
      AND TAM.RATING_ACCT_NBR = TOP.RATING_ACCT_NBR
      AND TAM.REFACTORED_FLAG = 'T'
      AND TOP.TOMS_OBJECT_ID = TOM.OBJECT_ID
      AND TOP.TOMS_OBJECT_ID = BILLEVENTSUM.GROUP_ATTR_5
      AND TOP.TARIFF_ID = TF.TARIFF_ID
      AND TF.TARIFF_NAME = BILLEVENTSUM.GROUP_ATTR_3
      AND TF.CATALOGUE_CHANGE_ID = (SELECT CATALOGUE_CHANGE_ID FROM CATALOGUECHANGE C WHERE C.RATING_CATALOGUE_ID IN (  SELECT RATING_CATALOGUE_ID FROM RATINGCATALOGUE WHERE CATALOGUE_STATUS=3  AND CURRENCY_CODE = 'USD'
      AND INVOICING_CO_ID = 2) AND C.CATALOGUE_STATUS=3)
      AND BILLEVENTSUM.EVENT_SUMMARY_ID = EVENTSUM.EVENT_SUMMARY_ID
      AND BILLEVENTSUM.EVENT_SUMMARY_ID IN (85)) TMO_TEST WHERE  TMO_TEST.RATING_CUST_REF = SUB_HSD_CREDIT.CUSTOMER_REF 
  GROUP BY 
	  TMO_TEST.GROUP_ATTR_1, 
	  SUB_HSD_CREDIT.MSISDN, 
	  SUB_HSD_CREDIT.PLAN_NAME, 
	  SUB_HSD_CREDIT.PRODUCT_NAME, 
	  SUB_HSD_CREDIT.BUCKET_LIMIT, 
	  TMO_TEST.GROUP_ATTR_3, 
	  TMO_TEST.ACCOUNT_NUM, 
	  TMO_TEST.BILL_SEQ, 
	  TMO_TEST.CHARGING_RATE, 
	  TMO_TEST.GROUP_ATTR_5, 
	  TMO_TEST.GROUP_ATTR_6, 
	  TMO_TEST.SUM_ATTR_3, 
	  TMO_TEST.EVENT_SUMMARY_ID, 
	  DECODE(TMO_TEST.GROUP_ATTR_16,'UNKNOWN','',TMO_TEST.GROUP_ATTR_16)
WITH READ ONLY;
GRANT SELECT ON TMOBILE_CUSTOM.SUBHSDCREDIT_VIEW TO UNIF_ADMIN;

--For Suspend-Dormancy MRC type lineItemDetails:
CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."SUBSUSPENDDAYS_VIEW" AS
SELECT DISTINCT 
TAM.BILLING_ACCT_NBR ACCOUNT_NUM,
ACTDAYS.MSISDN,
ACTDAYS.SUSPENDDAYS,
BILLEVENTSUM.GROUP_ATTR_3 BILLING_TARIFF_NAME,
CONFIG.TOMS_OBJECT_ID TLO_OBJECT_ID,
CONFIG.PPA_NAME FEE_TYPE,
BS.BILL_SEQ,
CONFIG.PPA_NAME_DESCRIPTION DESCRIPTION 
FROM 
PVBILLEVENTSUMMARY6 BILLEVENTSUM,
TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM,
TARIFF TF,
TMOBILE_CUSTOM.TMO_INVOICE_ACTIVESUSPENDDAYS ACTDAYS,
TMOBILE_CUSTOM.TMO_MRC_CONFIG CONFIG,
BILLSUMMARY BS
WHERE TAM.BILLING_ACCT_NBR = BILLEVENTSUM.ACCOUNT_NUM
AND TAM.RATING_CUST_REF = ACTDAYS.CUSTOMER_REF
AND TF.TARIFF_NAME = BILLEVENTSUM.GROUP_ATTR_3
AND TF.CATALOGUE_CHANGE_ID = (SELECT CATALOGUE_CHANGE_ID FROM CATALOGUECHANGE C WHERE C.RATING_CATALOGUE_ID IN (SELECT RATING_CATALOGUE_ID FROM RATINGCATALOGUE WHERE CATALOGUE_STATUS=3  AND CURRENCY_CODE = 'USD'
AND INVOICING_CO_ID = 2) AND C.CATALOGUE_STATUS=3)
AND CONFIG.TOMS_OBJECT_ID = BILLEVENTSUM.GROUP_ATTR_5
AND CONFIG.PPA_NAME = BILLEVENTSUM.GROUP_ATTR_7
AND TAM.BILLING_ACCT_NBR = BS.ACCOUNT_NUM
AND BS.EVENT_SEQ = ACTDAYS.EVENT_SEQ
AND BS.BILL_VERSION = (SELECT MAX(BILL_VERSION) FROM BILLSUMMARY B WHERE B.ACCOUNT_NUM=BS.ACCOUNT_NUM AND B.BILL_SEQ=BS.BILL_SEQ  AND BS.BILL_STATUS IN (1,7,8))
AND ACTDAYS.SUSPENDDAYS != 0
WITH READ ONLY;

GRANT SELECT ON TMOBILE_CUSTOM.SUBSUSPENDDAYS_VIEW TO UNIF_ADMIN;

--For Access Fee MRC type lineItemDetails:
CREATE OR REPLACE  VIEW "TMOBILE_CUSTOM"."ACCESSFEE_VIEW"("PARTNER_NAME","MSISDN","ACTIVEDAYS","SUSPENDDAYS", "BILLING_TARIFF_NAME", "ACCOUNT_NUM","BILL_SEQ", "CHARGING_RATE", "TLO_OBJECT_ID", "COST_BAND", "QUANTITY", "EVENT_SUMMARY_ID", "TECH_TYPE") AS 
SELECT TMO_TEST.CUSTOMER_NAME,ACTDAYS.MSISDN, ACTDAYS.ACTIVEDAYS, ACTDAYS.SUSPENDDAYS, TMO_TEST.GROUP_ATTR_3 as BILLING_TARIFF_NAME, TMO_TEST.ACCOUNT_NUM, TMO_TEST.BILL_SEQ,
TMO_TEST.CHARGING_RATE,TMO_TEST.GROUP_ATTR_5,TMO_TEST.GROUP_ATTR_6, 
TMO_TEST.SUM_ATTR_3, TMO_TEST.EVENT_SUMMARY_ID,DECODE(TMO_TEST.GROUP_ATTR_16,'UNKNOWN','',TMO_TEST.GROUP_ATTR_16)
FROM TMOBILE_CUSTOM.TMO_INVOICE_ACTIVESUSPENDDAYS ACTDAYS,  
(SELECT 
      EVENTSUM.EVENT_SUMMARY_NAME,
      BILLEVENTSUM.ACCOUNT_NUM, --ACC_NUM
      TAM.CUSTOMER_NAME, --PARTNER_NAME
	  BILLEVENTSUM.GROUP_ATTR_6, --COST_BAND
      BILLEVENTSUM.GROUP_ATTR_3, --BILLING TARIFF NAME
	  ROUND(TO_NUMBER(BILLEVENTSUM.GROUP_ATTR_4)/1000000,5) CHARGING_RATE,
      BILLEVENTSUM.GROUP_ATTR_5, --TLO OBJECT ID
	  BILLEVENTSUM.GROUP_ATTR_16,
	  BILLEVENTSUM.SUM_ATTR_1, -- Quantity
	  BILLEVENTSUM.SUM_ATTR_3,	
	  BILLEVENTSUM.EVENT_SUMMARY_ID,
      TOP.SEQ TLO_OBJECT_SEQUENCE,
      TOM.OBJECT_NAME TOMS_OFFER_NAME,
      TF.TARIFF_ID,
	  BILLEVENTSUM.BILL_SEQ,
	  TAM.RATING_CUST_REF
  FROM 
      PVBILLEVENTSUMMARY6 BILLEVENTSUM, 
      PVEVENTSUMMARY2 EVENTSUM,
      TMOBILE_CUSTOM.TOMS_OFFERNAMEMAPPING TOM,
      TMOBILE_CUSTOM.TMO_OFFERPLANID_80 TOP,
      TMOBILE_CUSTOM.TMO_ACCT_MAPPING TAM,
      TARIFF TF
  WHERE TAM.BILLING_ACCT_NBR = BILLEVENTSUM.ACCOUNT_NUM
    AND TAM.BILLING_EVENT_SRC = BILLEVENTSUM.GROUP_ATTR_1
      AND TAM.RATING_ACCT_NBR = TOP.RATING_ACCT_NBR
      AND TAM.REFACTORED_FLAG = 'T'
      AND TOP.TOMS_OBJECT_ID = TOM.OBJECT_ID
      AND TOP.TOMS_OBJECT_ID = BILLEVENTSUM.GROUP_ATTR_5
      AND TOP.TARIFF_ID = TF.TARIFF_ID
      --AND TF.TARIFF_NAME = BILLEVENTSUM.GROUP_ATTR_3
      AND TF.CATALOGUE_CHANGE_ID = (SELECT CATALOGUE_CHANGE_ID FROM CATALOGUECHANGE C WHERE C.RATING_CATALOGUE_ID IN (  SELECT RATING_CATALOGUE_ID FROM RATINGCATALOGUE WHERE CATALOGUE_STATUS=3  AND CURRENCY_CODE = 'USD'
      AND INVOICING_CO_ID = 2) AND C.CATALOGUE_STATUS=3)
      AND BILLEVENTSUM.EVENT_SUMMARY_ID = EVENTSUM.EVENT_SUMMARY_ID
      AND BILLEVENTSUM.EVENT_SUMMARY_ID IN (85)) TMO_TEST 
	  WHERE TMO_TEST.GROUP_ATTR_5 = ACTDAYS.TOMS_OBJECT_ID AND TMO_TEST.TARIFF_ID = ACTDAYS.TARIFF_ID AND 
      TMO_TEST.GROUP_ATTR_3  IN  (SELECT TARIFF_NAME FROM TARIFF , TMOBILE_CUSTOM.TMO_INVOICE_ACTIVESUSPENDDAYS ACTDAYS1 WHERE 
      ACTDAYS1.TARIFF_ID = TARIFF.TARIFF_ID) AND TMO_TEST.RATING_CUST_REF = ACTDAYS.CUSTOMER_REF 
  GROUP BY 
	  TMO_TEST.CUSTOMER_NAME, 
	  ACTDAYS.MSISDN, 
	  ACTDAYS.ACTIVEDAYS, 
	  ACTDAYS.SUSPENDDAYS, 
	  TMO_TEST.GROUP_ATTR_3, 
	  TMO_TEST.ACCOUNT_NUM, 
	  TMO_TEST.BILL_SEQ, 
	  TMO_TEST.CHARGING_RATE, 
	  TMO_TEST.GROUP_ATTR_5, 
	  TMO_TEST.GROUP_ATTR_6, 
	  TMO_TEST.SUM_ATTR_3, 
	  TMO_TEST.EVENT_SUMMARY_ID, 
	  DECODE(TMO_TEST.GROUP_ATTR_16,'UNKNOWN','',TMO_TEST.GROUP_ATTR_16)
 WITH READ ONLY;
GRANT SELECT ON TMOBILE_CUSTOM.ACCESSFEE_VIEW TO UNIF_ADMIN;
