BEGIN
  execute immediate 'DROP TABLE TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
CREATE TABLE TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
(
  ACCT_TYPE VARCHAR2(30),
  SUM_RATING_TARIFF_ID NUMBER,
   CONSTRAINT  TMO_POB_RATE_SUM_MAPPING_PK PRIMARY KEY (ACCT_TYPE,SUM_RATING_TARIFF_ID)
)
 TABLESPACE "USERS";
 INSERT ALL INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
      (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
    VALUES
      ('MVNO', 1000) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
      (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
    VALUES
      ('MVNO', 1060) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
    VALUES
      ('MVNO', 1061) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('MVNO', 1062) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('MVNO', 1063) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('MVNO', 1064) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('MVNO', 1065) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('MVNO', 1067) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('MVNO', 1002) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('M2M', 1000) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('M2M', 1060) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('M2M', 1061) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('M2M', 1062) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('M2M', 1063) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('M2M', 1064) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('M2M', 1065) INTO TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING
	  (ACCT_TYPE,
       SUM_RATING_TARIFF_ID)
	VALUES
      ('M2M', 1067)
	  SELECT * FROM DUAL;
	  COMMIT;
	  
GRANT ALL ON TMOBILE_CUSTOM.TMO_POB_RATE_SUM_MAPPING TO GENEVA_ADMIN,UNIF_ADMIN,GENEVABATCHUSER;

