CREATE OR REPLACE VIEW TMOBILE_CUSTOM.TMO_CONTACT_VIEW ("CUSTOMER_REF","CONTACT_NAME","CONTACT_SURNAME","CONTACT_EMAIL","CONTACT_PHONE","CONTACT_POSITION") AS
SELECT CON.CUSTOMER_REF,CON.FIRST_NAME, CON.LAST_NAME, CONDETAILS.EMAIL_ADDRESS,CONDETAILS.DAYTIME_CONTACT_TEL, CONDETAILS.POSITION
FROM GENEVA_ADMIN.CONTACT CON,
GENEVA_ADMIN.CONTACTDETAILS CONDETAILS,
TMOBILE_CUSTOM.TMO_ACCT_MAPPING ACCT
WHERE  ACCT.RATING_CUST_REF = CON.CUSTOMER_REF
AND CON.CUSTOMER_REF = CONDETAILS.CUSTOMER_REF
AND CON.CONTACT_SEQ = (SELECT MAX(CONTACT_SEQ) FROM CONTACT WHERE CUSTOMER_REF = ACCT.RATING_CUST_REF)
AND CONDETAILS.CONTACT_SEQ = CON.CONTACT_SEQ
AND CONDETAILS.ADDRESS_SEQ = (SELECT MAX(ADDRESS_SEQ) FROM CONTACTDETAILS WHERE CUSTOMER_REF = ACCT.RATING_CUST_REF)
WITH READ ONLY;

GRANT SELECT ON TMOBILE_CUSTOM.TMO_CONTACT_VIEW TO PUBLIC;
CREATE OR REPLACE PUBLIC SYNONYM TMO_CONTACT_VIEW FOR TMOBILE_CUSTOM.TMO_CONTACT_VIEW;


