BEGIN
  execute immediate 'DROP TABLE TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
CREATE TABLE TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING
(
  EVENT_TYPE_NAME VARCHAR2(30),
  RATING_TARIFF_ID NUMBER,
   CONSTRAINT  TMO_POB_RATE_PLAN_MAPPING_PK PRIMARY KEY (EVENT_TYPE_NAME,RATING_TARIFF_ID)
)
 TABLESPACE "USERS";
 INSERT ALL INTO TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING
      (EVENT_TYPE_NAME,
       RATING_TARIFF_ID)
    VALUES
      ('Voice', 2173) INTO TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING
      (EVENT_TYPE_NAME,
       RATING_TARIFF_ID)
    VALUES
      ('SMS', 2172) INTO TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING
	  (EVENT_TYPE_NAME,
       RATING_TARIFF_ID)
    VALUES
      ('GPRS', 2168) INTO TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING
	  (EVENT_TYPE_NAME,
       RATING_TARIFF_ID)
    VALUES
      ('MMS', 2171) INTO TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING
	  (EVENT_TYPE_NAME,
       RATING_TARIFF_ID)
    VALUES
      ('Intl Voice', 2170) INTO TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING
	  (EVENT_TYPE_NAME,
       RATING_TARIFF_ID)
    VALUES
      ('Intl SMS', 2174) INTO TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING
	  (EVENT_TYPE_NAME,
       RATING_TARIFF_ID)
    VALUES
      ('Intl GPRS', 2169) 
	  SELECT * FROM DUAL;
	  COMMIT;
	
GRANT ALL ON TMOBILE_CUSTOM.TMO_POB_RATE_PLAN_MAPPING TO GENEVA_ADMIN,UNIF_ADMIN,GENEVABATCHUSER;