prompt PL/SQL Developer import file
prompt Created on Monday, January 16, 2017 by nako02141
set feedback off
set define off
prompt Disabling triggers for TMO_GLLINEITEMTEXTMAP...
alter table TMO_GLLINEITEMTEXTMAP disable all triggers;
prompt Deleting TMO_GLLINEITEMTEXTMAP...
delete from TMO_GLLINEITEMTEXTMAP;
commit;
prompt Loading TMO_GLLINEITEMTEXTMAP...
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50130025', '50130025', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50110035', '50110035', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50130050', '50130050', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530100', '44530100', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530050', '44530050', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530010', '44530010', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('99999002', '99999002', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('80000010', '80000010', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('80000030', '80000030', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('80000040', '80000040', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530070', '44530070', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530150', '44530150', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50130030', '50130030', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530200', '44530200', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530030', '44530030', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50110160', '50110160', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50010050', '50010050', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50130130', '50130130', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('99999107', '99999107', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('99999003', '99999003', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530080', '44530080', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530210', '44530210', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530260', '44530260', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('99999105', '99999105', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('99999999', '99999999', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('80000020', '80000020', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530120', '44530120', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530280', '44530280', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530220', '44530220', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50050020', '50050020', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530060', '44530060', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('24030016', '24030016', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50010020', '50010020', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('80000060', '80000060', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('49070030', '49070030', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530020', '44530020', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530090', '44530090', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50120160', '50120160', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('50110025', '50110025', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('99999001', '99999001', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('99999500', '99999500', 'REVENUE', 'PROFIT', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530180', '44530180', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530040', '44530040', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('44530110', '44530110', 'REVENUE', 'BALANCE SHEET', null, 'T');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('AVD', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('1_Federal Excise Tax', '44530060', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('1_Service Tax-Oth', '44530180', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('1_Special Tax', '44530060', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('1_Telecoms Relay Service Surcharge WN', '44530070', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('1_Universal Service Fund Surcharge WN', '44530050', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('1_Universal Service Fund Surcharge WS', '44530050', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_911 Tax', '44530020', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_911 Tax Wireless', '44530020', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_DEAF Surcharge', '44530040', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_DEAF Surcharge Wireless', '44530040', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_District Tax', '44530180', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_High Cost Fund Surcharge', '44530090', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_High Cost Fund Surcharge Wireless', '44530090', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_License Tax', '44530110', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_License Tax Wireless', '44530110', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Lifeline', '44530120', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_PUC Tax', '44530150', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Poison Control Surcharge', '44530010', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Poison Control Surcharge Wireless', '44530010', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Sales Tax', '44530180', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Statutory Gross Receipts Tax', '44530080', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_T-Mobile Customized', '50130030', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Telecoms Relay Service Surcharge WN', '44530200', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Telecoms Relay Service Surcharge WS', '44530200', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Universal Service Fund Surcharge WN', '44530280', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Utility Users Tax', '44530260', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_Utility Users Tax, Wireless', '44530260', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('3_Statutory Gross Receipts Tax Wireless', '44530080', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('3_Surcharge', '44530210', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('3_Telephone Sales Tax', '44530180', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('3_Utility Users Tax Business', '44530260', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('4_911 Tax Business', '44530020', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('4_Business & Occupation Tax', '44530030', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('4_Business & Occupation Tax Wireless', '44530030', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('4_Excise Tax', '44530220', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('4_Service Tax', '44530180', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('4_Utility Users Tax Business, Wireless', '44530260', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj  MRC - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Airtime - Wholesale', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Airtime Usage - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Courtesy - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj GPRS Usage - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj GPRS Usage - Wholesale', '50130025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Intl GPRS Usage - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Intl Roaming GPRS Usage - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Intl Roaming SMS Usage - M2M', '50110160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Intl Roaming Voice Usage - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Intl SMS Usage - M2M', '50110160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Intl Voice Usage - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj MMS Usage - Wholesale', '50110035', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Other Service Fee Revenue -Wholesale', '50130050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Premium Service Charge - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj SMS Usage - M2M', '50110160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj SMS Usage - Wholesale', '50110025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Subscriber Roaming - Wholesale', '50050020', 'REVENUE', 'PROFIT', null, 'F');
commit;
prompt 100 records committed...
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adj Toll - Wholesale', '50010050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Adjustment', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Call Support Overage', '50130050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Discount', '50130050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Discount - SMS Roaming', '50110025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Discount - Voice Roaming', '50050020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Excise Tax', '44530100', 'REVENUE', 'BALANCE SHEET', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('GPRS MRC Advance', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Gross Activation', '50130050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Misc Adjustment', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Misc Adjustment - M2M', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Monthly Minimum Payment', '24030016', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Other Service Fee Revenue', '50130050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Product Charges', '50130050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Recovery Fee', '50130130', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Special Incentive', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Undefined', '99999999', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V Adj Subscriber Roaming - VAR', '80000060', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V Call Support Overage', '80000010', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('1_GPRS MRC Advance', '49070030', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('2_GPRS MRC Advance', '24030016', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('3_GPRS MRC Advance', '49070030', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Access Fee', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Airtime', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Airtime ILD', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Dormancy Fee', '50130050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('GPRS', '50130025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('GPRS MRC', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('GPRS-BLKBRY', '50130025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('MMS', '50110035', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('MRC', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Payment', '24030016', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Roam Mobility Subscriber Package', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Roaming', '50050020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Roaming ILD', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('SMS', '50110025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Simple Datastick Package 1 Final', '50130025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Simple Datastick Package 2 Final', '50130025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Simple Datastick Package 3 Final', '50130025', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Simple Subscriber Package 1', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Simple Subscriber Package 2', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Simple Subscriber Package 3', '50010020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('TOLL Directory Assistance', '50010050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('TOLL International', '50010050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Twilio Airtime', '99999001', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Twilio GPRS', '99999107', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Twilio GPRS MRC', '99999500', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Twilio Roaming', '99999003', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Twilio SMS', '99999105', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Twilio TOLL Directory Assistance', '99999002', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Twilio TOLL International', '99999002', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Twilio TOLL Long Distance', '99999002', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V Airtime', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V Event Discount Amounts', '80000030', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V GPRS', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V Package Discount Amounts', '80000040', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V Product Discount Amounts', '80000020', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V Roaming', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V SMS', '50110160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V TOLL Directory Assistance', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V TOLL International', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('V TOLL Long Distance', '50120160', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('Suspend', '50130050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('TOLL Long Distance', '50010050', 'REVENUE', 'PROFIT', null, 'F');
insert into TMO_GLLINEITEMTEXTMAP (LINE_ITEM_TEXT, GL_ACCOUNT, CATEGORY_IND, REPORTING_IND, GL_ACCOUNT_DESCRIPTION, READONLY_FLAG)
values ('REV Offset', '24030016', 'OFFSET', 'BALANCE SHEET', null, 'F');
commit;
prompt 165 records loaded
prompt Enabling triggers for TMO_GLLINEITEMTEXTMAP...
alter table TMO_GLLINEITEMTEXTMAP enable all triggers;
set feedback on
set define on
prompt Done.
