BEGIN
  execute immediate 'DROP TABLE TMOBILE_CUSTOM.TMO_CUSTOM_EVENT_TYPE';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  execute immediate 'DROP TABLE TMOBILE_CUSTOM.TMO_EVENT_MAPPING';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

CREATE TABLE "TMOBILE_CUSTOM"."TMO_EVENT_MAPPING" 
("EVENT_SUMMARY_ID" NUMBER(9,0) NOT NULL ENABLE, 
"EVENT_SUMMARY_NAME" VARCHAR2(40) NOT NULL ENABLE,  
"SUMMARY_EVENT_TYPE" NUMBER(9,0) NOT NULL ENABLE, 
"EVENT_TYPE" NUMBER(9,0), 
CONSTRAINT "TMO_EVENT_MAPPING_PK" PRIMARY KEY ("EVENT_SUMMARY_ID")
)
TABLESPACE "USERS" ;
GRANT SELECT ON TMOBILE_CUSTOM.TMO_EVENT_MAPPING TO UNIF_ADMIN;
Grant select, insert, delete on TMOBILE_CUSTOM.TMO_EVENT_MAPPING to geneva_admin;

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (78, 'Genesis_GL-Invoice_Sum_Voice', 33, 1);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (79, 'Genesis_GL-Invoice_Sum_SMS', 37, 2);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (80, 'Genesis_GL-Invoice_Sum_GPRS', 35, 3);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (81, 'Genesis_GL-Invoice_Sum_MMS', 39, 4);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (82, 'Genesis_GL-Invoice_Sum_Intl_Voice', 34, 20);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (83, 'Genesis_GL-Invoice_Sum_Intl_SMS', 38, 28);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (84, 'Genesis_GL-Invoice_Sum_Intl_GPRS', 36, 21);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE)
values (85, 'Genesis_GL-Invoice_Sum_MRC', 46);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (86, 'Genesis_GL-Invoice_Sum_Dist_Adj', 42, -1);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (87, 'Genesis_GL-Invoice_MVNO_Sum_Voice_Ovg', 43, -1);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (88, 'Genesis_GL-Invoice_MVNO_Sum_SMS_Ovg', 44, -1);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (89, 'Genesis_GL-Invoice_MVNO_Sum_GPRS_Ovg', 45, -1);

insert into TMOBILE_CUSTOM.TMO_EVENT_MAPPING (EVENT_SUMMARY_ID, EVENT_SUMMARY_NAME, SUMMARY_EVENT_TYPE, EVENT_TYPE)
values (92, 'Genesis_GL-Invoice_Sum_Voice_Toll', 33, 1);

COMMIT;
